# Generated by Django 6.0.3 on 2026-05-01 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        ('elevage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identifiant court unique, ex : ENERGIE, MAINTENANCE.', max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=150, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la dépense')),
                ('description', models.CharField(max_length=500, verbose_name='Description / Objet')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant (DZD)')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('carte', 'Carte bancaire'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('reference_document', models.CharField(blank=True, help_text='Numéro de la pièce justificative papier.', max_length=150, verbose_name='Référence document (facture / reçu)')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='depenses/%Y/%m/', verbose_name='Pièce jointe (PDF/JPG/PNG)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='depenses.categoriedepense', verbose_name='Catégorie')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('facture_liee', models.ForeignKey(blank=True, help_text='Uniquement pour les factures de type Service. Ne jamais relier une facture de marchandises (BR-DEP-01).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_liees', to='achats.facturefournisseur', verbose_name='Facture fournisseur liée (service uniquement)')),
                ('lot', models.ForeignKey(blank=True, help_text='Optionnel — pour le calcul de rentabilité par lot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='elevage.lotelevage', verbose_name='Lot attribué')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
