# Generated by Django 6.0.3 on 2026-05-14 10:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_alter_acomptefournisseur_options_and_more'),
        ('depenses', '0001_initial'),
        ('elevage', '0002_alter_consommation_options_alter_lotelevage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriedepense',
            options={'ordering': ['ordre', 'libelle'], 'verbose_name': 'فئة المصروف', 'verbose_name_plural': 'فئات المصاريف'},
        ),
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'مصروف', 'verbose_name_plural': 'مصاريف'},
        ),
        migrations.AlterField(
            model_name='categoriedepense',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='categoriedepense',
            name='code',
            field=models.CharField(help_text='معرف قصير فريد، مثال: ENERGIE, MAINTENANCE.', max_length=50, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='categoriedepense',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='categoriedepense',
            name='libelle',
            field=models.CharField(max_length=150, verbose_name='التسمية'),
        ),
        migrations.AlterField(
            model_name='categoriedepense',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='depenses.categoriedepense', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='date',
            field=models.DateField(verbose_name='تاريخ المصروف'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='description',
            field=models.CharField(max_length=500, verbose_name='الوصف / الموضوع'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='مسجّل من قبل'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='facture_liee',
            field=models.ForeignKey(blank=True, help_text='للفواتير من نوع الخدمة فقط. لا تربط أبداً بفاتورة بضائع (BR-DEP-01).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_liees', to='achats.facturefournisseur', verbose_name='فاتورة المورد المرتبطة (خدمة فقط)'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='اختياري — لحساب الربحية لكل دفعة.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='elevage.lotelevage', verbose_name='الدفعة المخصصة'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'نقداً'), ('cheque', 'شيك'), ('virement', 'تحويل بنكي'), ('carte', 'بطاقة بنكية'), ('autre', 'أخرى')], default='especes', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ (د.ج)'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='depenses/%Y/%m/', verbose_name='مرفق (PDF/JPG/PNG)'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='reference_document',
            field=models.CharField(blank=True, help_text='رقم الوثيقة المثبتة الورقية.', max_length=150, verbose_name='مرجع الوثيقة (فاتورة / وصل)'),
        ),
    ]
