# Generated by Django 4.2.30 on 2026-07-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='piece_jointe',
        ),
        migrations.RemoveField(
            model_name='retraitassocie',
            name='piece_jointe',
        ),
    ]
