# Generated by Django 6.0.3 on 2026-06-19 21:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_alter_categoriedepense_options_alter_depense_options_and_more'),
        ('intrants', '0002_alter_batiment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='الاسم')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('pourcentage_parts', models.DecimalField(blank=True, decimal_places=2, help_text='معلوماتي فقط — لا يُستخدم لحساب أو تحديد سقف السحوبات.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الحصة (%)')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True, verbose_name='الرقم التعريفي')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('fonction', models.CharField(blank=True, max_length=100, verbose_name='الوظيفة')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('date_embauche', models.DateField(verbose_name='تاريخ التوظيف')),
                ('jour_repos_habituel', models.PositiveSmallIntegerField(choices=[(0, 'الإثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], default=4, verbose_name='يوم الراحة الأسبوعي')),
                ('salaire_base_mensuel', models.DecimalField(decimal_places=2, help_text='مرجعي لـ 25 يوم عمل/الشهر (BR-RH-02).', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='الراتب الأساسي الشهري (د.ج)')),
                ('heures_normales_jour', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='ساعات العمل العادية/اليوم')),
                ('taux_majoration_heure_sup', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='مثال: 1.50 = زيادة 50% عن السعر العادي للساعة.', max_digits=3, verbose_name='معامل الساعات الإضافية')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='intrants.batiment', verbose_name='المبنى المخصص')),
                ('binome', models.ForeignKey(blank=True, help_text='العامل الذي يعمل بدلاً عنه يوم راحته (BR-RH-01).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplace_pour', to='depenses.employe', verbose_name='الزميل البديل (دوران)')),
            ],
            options={
                'verbose_name': 'عامل',
                'verbose_name_plural': 'العمال',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='CongeEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='من تاريخ')),
                ('date_fin', models.DateField(verbose_name='إلى تاريخ')),
                ('nb_jours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الأيام المخصومة')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='depenses.employe', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'عطلة عامل',
                'verbose_name_plural': 'عطل العمال',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('mois', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر')),
                ('jours_presence', models.PositiveSmallIntegerField(default=0, verbose_name='أيام الحضور')),
                ('jours_absence', models.PositiveSmallIntegerField(default=0, verbose_name='أيام الغياب')),
                ('jours_repos', models.PositiveSmallIntegerField(default=0, verbose_name='أيام الراحة')),
                ('jours_conge', models.PositiveSmallIntegerField(default=0, verbose_name='أيام العطلة المدفوعة')),
                ('total_heures_supplementaires', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='إجمالي الساعات الإضافية')),
                ('salaire_base_reference', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الراتب الأساسي المرجعي')),
                ('taux_journalier', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر اليومي')),
                ('montant_heures_sup', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='مبلغ الساعات الإضافية')),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الإجمالي (خام)')),
                ('total_acomptes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي التسبيقات')),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الصافي')),
                ('statut', models.CharField(choices=[('brouillon', 'مسودة'), ('valide', 'مصادق عليه'), ('paye', 'مدفوع')], default='brouillon', max_length=10, verbose_name='الحالة')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('mode_paiement', models.CharField(choices=[('especes', 'نقداً'), ('cheque', 'شيك'), ('virement', 'تحويل بنكي'), ('carte', 'بطاقة بنكية'), ('autre', 'أخرى')], default='virement', max_length=20, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_paie_generes', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ من قبل')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins_paie', to='depenses.employe', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'كشف راتب',
                'verbose_name_plural': 'كشوف الرواتب',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='AcompteEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ التسبيق')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ (د.ج)')),
                ('mode_paiement', models.CharField(choices=[('especes', 'نقداً'), ('cheque', 'شيك'), ('virement', 'تحويل بنكي'), ('carte', 'بطاقة بنكية'), ('autre', 'أخرى')], default='especes', max_length=20, verbose_name='طريقة الدفع')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acomptes_employes_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='مسجّل من قبل')),
                ('bulletin_paie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acomptes_deduits', to='depenses.bulletinpaie', verbose_name='مخصوم من كشف الراتب')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acomptes', to='depenses.employe', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'تسبيق على الراتب',
                'verbose_name_plural': 'تسبيقات على الرواتب',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('statut', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('repos', 'راحة أسبوعية'), ('conge', 'في عطلة مدفوعة')], default='present', max_length=10, verbose_name='الحالة')),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ساعات إضافية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='depenses.employe', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'تسجيل حضور',
                'verbose_name_plural': 'تسجيلات الحضور',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RetraitAssocie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ السحب')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ (د.ج)')),
                ('mode_paiement', models.CharField(choices=[('especes', 'نقداً'), ('cheque', 'شيك'), ('virement', 'تحويل بنكي'), ('carte', 'بطاقة بنكية'), ('autre', 'أخرى')], default='especes', max_length=20, verbose_name='طريقة الدفع')),
                ('motif', models.CharField(blank=True, help_text='مثال: سحب شخصي، تسبيق على الأرباح…', max_length=255, verbose_name='السبب')),
                ('reference_document', models.CharField(blank=True, max_length=150, verbose_name='مرجع الوثيقة')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='associes/retraits/%Y/%m/', verbose_name='مرفق (إيصال)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retraits', to='depenses.associe', verbose_name='الشريك')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='مسجّل من قبل')),
            ],
            options={
                'verbose_name': 'سحب شريك',
                'verbose_name_plural': 'سحوبات الشركاء',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bulletinpaie',
            constraint=models.UniqueConstraint(fields=('employe', 'annee', 'mois'), name='unique_bulletin_par_mois'),
        ),
        migrations.AddConstraint(
            model_name='pointage',
            constraint=models.UniqueConstraint(fields=('employe', 'date'), name='unique_pointage_par_jour'),
        ),
    ]
