# Generated by Django 4.2.30 on 2026-07-08 19:52

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depenses', '0002_remove_depense_piece_jointe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetteEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الدين')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='مبلغ الدين (د.ج)')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettes', to='depenses.employe', verbose_name='العامل')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettes_employes_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='مسجّل من قبل')),
            ],
            options={
                'verbose_name': 'دين عامل',
                'verbose_name_plural': 'ديون العمال',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='التاريخ')),
                ('nom', models.CharField(max_length=100, verbose_name='التسمية')),
                ('actif', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'يوم عيد / احتفال',
                'verbose_name_plural': 'أيام الأعياد والاحتفالات',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='jours_feries',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='أيام الأعياد المُشتغلة'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='montant_jours_feries',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='مبلغ أيام الأعياد الإضافي'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='total_dettes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي تسديد الديون'),
        ),
        migrations.CreateModel(
            name='RemboursementDette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ المخصوم (د.ج)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulletin_paie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements_dettes', to='depenses.bulletinpaie', verbose_name='كشف الراتب')),
                ('dette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='depenses.detteemploye', verbose_name='الدين')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_dettes_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='مسجّل من قبل')),
            ],
            options={
                'verbose_name': 'تسديد دين',
                'verbose_name_plural': 'تسديدات الديون',
                'ordering': ['-created_at'],
            },
        ),
    ]
