# Generated by Django 4.2.30 on 2026-07-10 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_livraisonpartielle_quantite_livree'),
        ('depenses', '0003_detteemploye_jourferie_bulletinpaie_jours_feries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='voyage',
            field=models.ForeignKey(blank=True, help_text='اختياري — لتخصيص تكلفة النقل لرحلة توصيل محددة.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_transport', to='clients.voyagelivraison', verbose_name='رحلة التوصيل المرتبطة'),
        ),
    ]
