# Generated by Django 6.0.3 on 2026-05-01 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intrants', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAjustement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('intrant', 'Stock Intrants'), ('produit_fini', 'Stock Produits Finis')], max_length=20, verbose_name='Segment de stock')),
                ('date_ajustement', models.DateField(verbose_name="Date de l'ajustement")),
                ('quantite_avant', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité avant ajustement')),
                ('quantite_apres', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité après ajustement')),
                ('raison', models.TextField(help_text="Obligatoire — décrivez l'écart constaté.", verbose_name='Raison / Justification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustements_stock', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('intrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustements', to='intrants.intrant', verbose_name='Intrant')),
                ('produit_fini', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustements', to='production.produitfini', verbose_name='Produit fini')),
            ],
            options={
                'verbose_name': 'Ajustement de stock',
                'verbose_name_plural': 'Ajustements de stock',
                'ordering': ['-date_ajustement'],
            },
        ),
        migrations.CreateModel(
            name='StockIntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantité en stock')),
                ('prix_moyen_pondere', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Prix moyen pondéré (DZD)')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('intrant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='intrants.intrant', verbose_name='Intrant')),
            ],
            options={
                'verbose_name': 'Stock intrant',
                'verbose_name_plural': 'Stocks intrants',
            },
        ),
        migrations.CreateModel(
            name='StockMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement')], max_length=20, verbose_name='Type')),
                ('source', models.CharField(choices=[('bl_fournisseur', 'BL Fournisseur'), ('consommation', 'Consommation lot'), ('production', 'Production'), ('bl_client', 'BL Client'), ('ajustement', 'Ajustement manuel')], max_length=30, verbose_name='Source')),
                ('quantite', models.DecimalField(decimal_places=3, help_text='Always positive; direction is given by type_mouvement.', max_digits=14, verbose_name='Quantité')),
                ('quantite_avant', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Stock avant')),
                ('quantite_apres', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Stock après')),
                ('date_mouvement', models.DateField(verbose_name='Date du mouvement')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID document source')),
                ('reference_label', models.CharField(blank=True, max_length=100, verbose_name='Référence document')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
                ('intrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='intrants.intrant', verbose_name='Intrant')),
                ('produit_fini', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='production.produitfini', verbose_name='Produit fini')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockProduitFini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantité en stock')),
                ('cout_moyen_production', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Coût moyen de production (DZD)')),
                ('seuil_alerte', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name="Seuil d'alerte")),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('produit_fini', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='production.produitfini', verbose_name='Produit fini')),
            ],
            options={
                'verbose_name': 'Stock produit fini',
                'verbose_name_plural': 'Stocks produits finis',
            },
        ),
    ]
