# Generated by Django 4.2.30 on 2026-06-30 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intrants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProduitFini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الكمية في المخزون')),
                ('cout_moyen_production', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='متوسط تكلفة الإنتاج (د.ج)')),
                ('seuil_alerte', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='حد التنبيه')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_produits_finis', to='core.branche', verbose_name='الفرع')),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='production.produitfini', verbose_name='المنتج النهائي')),
            ],
            options={
                'verbose_name': 'مخزون المنتج النهائي',
                'verbose_name_plural': 'مخازن المنتجات النهائية',
            },
        ),
        migrations.CreateModel(
            name='StockMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'إدخال'), ('sortie', 'إخراج'), ('ajustement', 'تسوية')], max_length=20, verbose_name='النوع')),
                ('source', models.CharField(choices=[('bl_fournisseur', 'وصل تسليم المورد'), ('consommation', 'استهلاك الدفعة'), ('production', 'الإنتاج'), ('bl_client', 'وصل تسليم العميل'), ('ajustement', 'تسوية يدوية'), ('mortalite', 'نفوق (خصم كتاكيت)'), ('ponte', 'إنتاج البيض (ponte)'), ('fertilisant', 'معالجة السماد'), ('livraison_abonnement', 'تسليم اشتراك عميل')], max_length=30, verbose_name='المصدر')),
                ('quantite', models.DecimalField(decimal_places=3, help_text='دائماً موجبة؛ الاتجاه يُحدده نوع الحركة.', max_digits=14, verbose_name='الكمية')),
                ('quantite_avant', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='المخزون قبل')),
                ('quantite_apres', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='المخزون بعد')),
                ('date_mouvement', models.DateField(verbose_name='تاريخ الحركة')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الوثيقة المصدر')),
                ('reference_label', models.CharField(blank=True, max_length=100, verbose_name='مرجع الوثيقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='core.branche', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
                ('intrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='intrants.intrant', verbose_name='المدخل')),
                ('produit_fini', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='production.produitfini', verbose_name='المنتج النهائي')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-date_mouvement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockIntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الكمية في المخزون')),
                ('prix_moyen_pondere', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='متوسط التكلفة الموزون (د.ج)')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_intrants', to='core.branche', verbose_name='الفرع')),
                ('intrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='intrants.intrant', verbose_name='المدخل')),
            ],
            options={
                'verbose_name': 'مخزون المدخلات',
                'verbose_name_plural': 'مخازن المدخلات',
            },
        ),
        migrations.CreateModel(
            name='StockAjustement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('intrant', 'مخزون المدخلات'), ('produit_fini', 'مخزون المنتجات النهائية')], max_length=20, verbose_name='قطاع المخزون')),
                ('date_ajustement', models.DateField(verbose_name='تاريخ التسوية')),
                ('quantite_avant', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='الكمية قبل التسوية')),
                ('quantite_apres', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='الكمية بعد التسوية')),
                ('raison', models.TextField(help_text='إلزامي — صف الفرق المُلاحظ.', verbose_name='السبب / المبرر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_stock', to='core.branche', verbose_name='الفرع')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustements_stock', to=settings.AUTH_USER_MODEL, verbose_name='منفذ من قبل')),
                ('intrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustements', to='intrants.intrant', verbose_name='المدخل')),
                ('produit_fini', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustements', to='production.produitfini', verbose_name='المنتج النهائي')),
            ],
            options={
                'verbose_name': 'تسوية مخزون',
                'verbose_name_plural': 'تسويات المخزون',
                'ordering': ['-date_ajustement'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockproduitfini',
            constraint=models.UniqueConstraint(fields=('branche', 'produit_fini'), name='unique_stock_produit_fini_par_branche'),
        ),
        migrations.AddConstraint(
            model_name='stockintrant',
            constraint=models.UniqueConstraint(fields=('branche', 'intrant'), name='unique_stock_intrant_par_branche'),
        ),
    ]
