# Generated by Django 4.2.30 on 2026-07-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_branche'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockajustement',
            name='branche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustements_stock', to='core.branche', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='stockintrant',
            name='branche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_intrants', to='core.branche', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='branche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='core.branche', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='stockproduitfini',
            name='branche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_produits_finis', to='core.branche', verbose_name='الفرع'),
        ),
    ]
