# Generated by Django 6.0.3 on 2026-05-14 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrants', '0002_alter_batiment_options_and_more'),
        ('production', '0002_alter_productionligne_options_and_more'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockajustement',
            options={'ordering': ['-date_ajustement'], 'verbose_name': 'تسوية مخزون', 'verbose_name_plural': 'تسويات المخزون'},
        ),
        migrations.AlterModelOptions(
            name='stockintrant',
            options={'verbose_name': 'مخزون المدخلات', 'verbose_name_plural': 'مخازن المدخلات'},
        ),
        migrations.AlterModelOptions(
            name='stockmouvement',
            options={'ordering': ['-date_mouvement', '-created_at'], 'verbose_name': 'حركة مخزون', 'verbose_name_plural': 'حركات المخزون'},
        ),
        migrations.AlterModelOptions(
            name='stockproduitfini',
            options={'verbose_name': 'مخزون المنتج النهائي', 'verbose_name_plural': 'مخازن المنتجات النهائية'},
        ),
        migrations.AlterField(
            model_name='stockajustement',
            name='date_ajustement',
            field=models.DateField(verbose_name='تاريخ التسوية'),
        ),
        migrations.AlterField(
            model_name='stockajustement',
            name='effectue_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustements_stock', to=settings.AUTH_USER_MODEL, verbose_name='منفذ من قبل'),
        ),
        migrations.AlterField(
            model_name='stockajustement',
            name='intrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustements', to='intrants.intrant', verbose_name='المدخل'),
        ),
        migrations.AlterField(
            model_name='stockajustement',
            name='produit_fini',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustements', to='production.produitfini', verbose_name='المنتج النهائي'),
        ),
        migrations.AlterField(
            model_name='stockajustement',
            name='quantite_apres',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='الكمية بعد التسوية'),
        ),
        migrations.AlterField(
            model_name='stockajustement',
            name='quantite_avant',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='الكمية قبل التسوية'),
        ),
        migrations.AlterField(
            model_name='stockajustement',
            name='raison',
            field=models.TextField(help_text='إلزامي — صف الفرق المُلاحظ.', verbose_name='السبب / المبرر'),
        ),
        migrations.AlterField(
            model_name='stockajustement',
            name='segment',
            field=models.CharField(choices=[('intrant', 'مخزون المدخلات'), ('produit_fini', 'مخزون المنتجات النهائية')], max_length=20, verbose_name='قطاع المخزون'),
        ),
        migrations.AlterField(
            model_name='stockintrant',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='stockintrant',
            name='intrant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='intrants.intrant', verbose_name='المدخل'),
        ),
        migrations.AlterField(
            model_name='stockintrant',
            name='prix_moyen_pondere',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='متوسط التكلفة الموزون (د.ج)'),
        ),
        migrations.AlterField(
            model_name='stockintrant',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الكمية في المخزون'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='date_mouvement',
            field=models.DateField(verbose_name='تاريخ الحركة'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='intrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='intrants.intrant', verbose_name='المدخل'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='produit_fini',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='production.produitfini', verbose_name='المنتج النهائي'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='quantite',
            field=models.DecimalField(decimal_places=3, help_text='دائماً موجبة؛ الاتجاه يُحدده نوع الحركة.', max_digits=14, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='quantite_apres',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='المخزون بعد'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='quantite_avant',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='المخزون قبل'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الوثيقة المصدر'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='reference_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='مرجع الوثيقة'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='source',
            field=models.CharField(choices=[('bl_fournisseur', 'وصل تسليم المورد'), ('consommation', 'استهلاك الدفعة'), ('production', 'الإنتاج'), ('bl_client', 'وصل تسليم العميل'), ('ajustement', 'تسوية يدوية')], max_length=30, verbose_name='المصدر'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('entree', 'إدخال'), ('sortie', 'إخراج'), ('ajustement', 'تسوية')], max_length=20, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='stockproduitfini',
            name='cout_moyen_production',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='متوسط تكلفة الإنتاج (د.ج)'),
        ),
        migrations.AlterField(
            model_name='stockproduitfini',
            name='produit_fini',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='production.produitfini', verbose_name='المنتج النهائي'),
        ),
        migrations.AlterField(
            model_name='stockproduitfini',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الكمية في المخزون'),
        ),
        migrations.AlterField(
            model_name='stockproduitfini',
            name='seuil_alerte',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='حد التنبيه'),
        ),
    ]
