# Generated by Django 6.0.3 on 2026-06-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stockajustement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmouvement',
            name='source',
            field=models.CharField(choices=[('bl_fournisseur', 'وصل تسليم المورد'), ('consommation', 'استهلاك الدفعة'), ('production', 'الإنتاج'), ('bl_client', 'وصل تسليم العميل'), ('ajustement', 'تسوية يدوية'), ('mortalite', 'نفوق (خصم كتاكيت)'), ('ponte', 'إنتاج البيض (ponte)'), ('fertilisant', 'معالجة السماد'), ('livraison_abonnement', 'تسليم اشتراك عميل')], max_length=30, verbose_name='المصدر'),
        ),
    ]
