# Generated by Django 6.0.3 on 2026-05-01 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='Wilaya')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('telephone_2', models.CharField(blank=True, max_length=30, verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name="NIF (Numéro d'identification fiscale)")),
                ('rc', models.CharField(blank=True, max_length=50, verbose_name='RC (Registre de Commerce)')),
                ('ai', models.CharField(blank=True, max_length=50, verbose_name="AI (Article d'imposition)")),
                ('nis', models.CharField(blank=True, max_length=50, verbose_name="NIS (Numéro d'identification statistique)")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('pied_de_page', models.TextField(blank=True, help_text='Texte affiché en bas des factures et BL imprimés.', verbose_name='Pied de page des documents')),
                ('regime_fiscal', models.CharField(blank=True, choices=[('reel', 'Régime réel'), ('forfait', 'Régime forfaitaire'), ('exonere', 'Exonéré')], default='reel', max_length=20, verbose_name='Régime fiscal')),
                ('assujetti_tva', models.BooleanField(default=True, help_text="Décocher si l'entreprise est exonérée de TVA.", verbose_name='Assujetti à la TVA')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19.0, help_text='Taux de TVA appliqué par défaut sur les documents (en %).', max_digits=5, verbose_name='Taux TVA (%)')),
                ('tap', models.CharField(blank=True, max_length=50, verbose_name="TAP (Taxe sur l'Activité Professionnelle)")),
                ('rib', models.CharField(blank=True, max_length=50, verbose_name='RIB / Compte bancaire')),
                ('banque', models.CharField(blank=True, max_length=150, verbose_name='Banque')),
                ('devise', models.CharField(default='DZD', max_length=10, verbose_name='Devise')),
                ('format_date', models.CharField(default='DD/MM/YYYY', help_text='Cosmétique uniquement — la base de données stocke ISO 8601.', max_length=20, verbose_name='Format de date affiché')),
                ('prefixe_bl_client', models.CharField(default='BLC', max_length=10, verbose_name='Préfixe BL Client')),
                ('prefixe_bl_fournisseur', models.CharField(default='BLF', max_length=10, verbose_name='Préfixe BL Fournisseur')),
                ('prefixe_facture_client', models.CharField(default='FAC', max_length=10, verbose_name='Préfixe Facture Client')),
                ('prefixe_facture_fournisseur', models.CharField(default='FRN', max_length=10, verbose_name='Préfixe Facture Fournisseur')),
            ],
            options={
                'verbose_name': "Informations de l'entreprise",
                'verbose_name_plural': "Informations de l'entreprise",
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gérant'), ('operateur', 'Opérateur'), ('comptable', 'Comptable')], default='operateur', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
