# Generated by Django 4.2.30 on 2026-06-30 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='اسم الفرع')),
                ('code', models.CharField(help_text='رمز قصير فريد يُستخدم في ترقيم الوثائق (مثال: EST, OUEST).', max_length=10, unique=True, verbose_name='الرمز')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='الولاية')),
                ('adresse', models.TextField(blank=True, verbose_name='العنوان')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef_de_branche', models.OneToOneField(blank=True, help_text="مستخدم بدور 'رئيس فرع' — مرتبط بهذا الفرع حصرياً (BR-BRA-02).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branche_dirigee', to=settings.AUTH_USER_MODEL, verbose_name='رئيس الفرع')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('adresse', models.TextField(verbose_name='العنوان')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='الولاية')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('telephone_2', models.CharField(blank=True, max_length=30, verbose_name='الهاتف 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF (الرقم الجبائي)')),
                ('rc', models.CharField(blank=True, max_length=50, verbose_name='RC (السجل التجاري)')),
                ('ai', models.CharField(blank=True, max_length=50, verbose_name='AI (المادة الضريبية)')),
                ('nis', models.CharField(blank=True, max_length=50, verbose_name='NIS (رقم التعريف الإحصائي)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='الشعار')),
                ('pied_de_page', models.TextField(blank=True, help_text='النص الظاهر أسفل الفواتير ووصولات التسليم المطبوعة.', verbose_name='تذييل الوثائق')),
                ('regime_fiscal', models.CharField(blank=True, choices=[('reel', 'النظام الحقيقي'), ('forfait', 'النظام الجزافي'), ('exonere', 'معفى')], default='reel', max_length=20, verbose_name='النظام الضريبي')),
                ('assujetti_tva', models.BooleanField(default=True, help_text='أزل التحديد إذا كانت الشركة معفاة من الضريبة على القيمة المضافة.', verbose_name='خاضع للضريبة على القيمة المضافة')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19.0, help_text='نسبة الضريبة المطبقة افتراضياً على الوثائق (بالمئة).', max_digits=5, verbose_name='نسبة الضريبة على القيمة المضافة (%)')),
                ('tap', models.CharField(blank=True, max_length=50, verbose_name='TAP (رسم النشاط المهني)')),
                ('rib', models.CharField(blank=True, max_length=50, verbose_name='RIB / حساب بنكي')),
                ('banque', models.CharField(blank=True, max_length=150, verbose_name='البنك')),
                ('devise', models.CharField(default='DZD', max_length=10, verbose_name='العملة')),
                ('format_date', models.CharField(default='DD/MM/YYYY', help_text='شكلي فقط — قاعدة البيانات تخزن بصيغة ISO 8601.', max_length=20, verbose_name='صيغة عرض التاريخ')),
                ('prefixe_bl_client', models.CharField(default='BLC', max_length=10, verbose_name='بادئة وصل تسليم العميل')),
                ('prefixe_bl_fournisseur', models.CharField(default='BLF', max_length=10, verbose_name='بادئة وصل تسليم المورد')),
                ('prefixe_facture_client', models.CharField(default='FAC', max_length=10, verbose_name='بادئة فاتورة العميل')),
                ('prefixe_facture_fournisseur', models.CharField(default='FRN', max_length=10, verbose_name='بادئة فاتورة المورد')),
            ],
            options={
                'verbose_name': 'معلومات الشركة',
                'verbose_name_plural': 'معلومات الشركة',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدير'), ('manager', 'مسيّر'), ('chef_branche', 'رئيس فرع'), ('operateur', 'مشغّل'), ('comptable', 'محاسب')], default='operateur', max_length=20, verbose_name='الدور')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branche', models.ForeignKey(blank=True, help_text='إلزامي لرئيس الفرع والمشغّل (BR-BRA-02). اختياري للمحاسب (فارغ = رؤية شاملة لجميع الفروع). يُترك فارغاً دائماً للمدير.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='core.branche', verbose_name='الفرع')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
