# Generated by Django 6.0.3 on 2026-05-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'معلومات الشركة', 'verbose_name_plural': 'معلومات الشركة'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ملف المستخدم', 'verbose_name_plural': 'ملفات المستخدمين'},
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='adresse',
            field=models.TextField(verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='ai',
            field=models.CharField(blank=True, max_length=50, verbose_name='AI (المادة الضريبية)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='assujetti_tva',
            field=models.BooleanField(default=True, help_text='أزل التحديد إذا كانت الشركة معفاة من الضريبة على القيمة المضافة.', verbose_name='خاضع للضريبة على القيمة المضافة'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='banque',
            field=models.CharField(blank=True, max_length=150, verbose_name='البنك'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='devise',
            field=models.CharField(default='DZD', max_length=10, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='format_date',
            field=models.CharField(default='DD/MM/YYYY', help_text='شكلي فقط — قاعدة البيانات تخزن بصيغة ISO 8601.', max_length=20, verbose_name='صيغة عرض التاريخ'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='nif',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIF (الرقم الجبائي)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='nis',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIS (رقم التعريف الإحصائي)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='pied_de_page',
            field=models.TextField(blank=True, help_text='النص الظاهر أسفل الفواتير ووصولات التسليم المطبوعة.', verbose_name='تذييل الوثائق'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='prefixe_bl_client',
            field=models.CharField(default='BLC', max_length=10, verbose_name='بادئة وصل تسليم العميل'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='prefixe_bl_fournisseur',
            field=models.CharField(default='BLF', max_length=10, verbose_name='بادئة وصل تسليم المورد'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='prefixe_facture_client',
            field=models.CharField(default='FAC', max_length=10, verbose_name='بادئة فاتورة العميل'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='prefixe_facture_fournisseur',
            field=models.CharField(default='FRN', max_length=10, verbose_name='بادئة فاتورة المورد'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='rc',
            field=models.CharField(blank=True, max_length=50, verbose_name='RC (السجل التجاري)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='regime_fiscal',
            field=models.CharField(blank=True, choices=[('reel', 'النظام الحقيقي'), ('forfait', 'النظام الجزافي'), ('exonere', 'معفى')], default='reel', max_length=20, verbose_name='النظام الضريبي'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='rib',
            field=models.CharField(blank=True, max_length=50, verbose_name='RIB / حساب بنكي'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tap',
            field=models.CharField(blank=True, max_length=50, verbose_name='TAP (رسم النشاط المهني)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='نسبة الضريبة المطبقة افتراضياً على الوثائق (بالمئة).', max_digits=5, verbose_name='نسبة الضريبة على القيمة المضافة (%)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=30, verbose_name='الهاتف 2'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير'), ('manager', 'مسيّر'), ('operateur', 'مشغّل'), ('comptable', 'محاسب')], default='operateur', max_length=20, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='الهاتف'),
        ),
    ]
