# Generated by Django 4.2.30 on 2026-07-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branche',
            field=models.ForeignKey(blank=True, help_text='إلزامي لرئيس الفرع والمشغّل (BR-BRA-02). اختياري للمحاسب (فارغ = رؤية شاملة لجميع الفروع). يُترك فارغاً دائماً للمدير.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='core.branche', verbose_name='الفرع'),
        ),
    ]
