# Generated by Django 4.2.30 on 2026-07-05 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_alter_userprofile_branche'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرّف السجل')),
                ('fichier', models.FileField(upload_to='pieces_jointes/%Y/%m/', verbose_name='الملف (PDF/JPG/PNG)')),
                ('type_document', models.CharField(choices=[('facture', 'فاتورة (نسخة ممسوحة)'), ('recu', 'إيصال'), ('virement', 'تأكيد تحويل بنكي'), ('bl', 'وصل تسليم (نسخة ممسوحة)'), ('cheque', 'صورة الشيك'), ('photo', 'صورة'), ('autre', 'أخرى')], default='autre', max_length=20, verbose_name='نوع الوثيقة')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='وصف مختصر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='contenttypes.contenttype', verbose_name='نوع السجل')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_jointes_ajoutees', to=settings.AUTH_USER_MODEL, verbose_name='أضيف من قبل')),
            ],
            options={
                'verbose_name': 'مرفق / وثيقة إثبات',
                'verbose_name_plural': 'المرفقات / وثائق الإثبات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_piecej_content_783ad4_idx')],
            },
        ),
    ]
