# Generated by Django 4.2.30 on 2026-07-10 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0004_depense_voyage'),
        ('core', '0003_piecejointe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employe',
            field=models.OneToOneField(blank=True, help_text='يُملأ تلقائياً عند إنشاء حساب مشغّل من بطاقة عامل (RH) — BR-RH-06.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_utilisateur', to='depenses.employe', verbose_name='العامل المرتبط'),
        ),
    ]
