# Generated by Django 4.2.30 on 2026-07-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير'), ('manager', 'مسيّر'), ('chef_branche', 'رئيس فرع'), ('operateur', 'مشغّل'), ('comptable', 'محاسب'), ('chauffeur', 'سائق')], default='operateur', max_length=20, verbose_name='الدور'),
        ),
    ]
