# Generated by Django 4.2.30 on 2026-06-30 22:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('intrants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotElevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='مثال: "دفعة أبريل 2025 – المبنى 1"', max_length=255, verbose_name='تسمية الدفعة')),
                ('date_ouverture', models.DateField(verbose_name='تاريخ الفتح')),
                ('date_fermeture', models.DateField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('statut', models.CharField(choices=[('ouvert', 'مفتوح'), ('ferme', 'مغلق')], default='ouvert', max_length=10, verbose_name='الحالة')),
                ('nombre_poussins_initial', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الكتاكيت الأولي')),
                ('souche', models.CharField(blank=True, help_text='مثال: Ross 308, Cobb 500', max_length=100, verbose_name='السلالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='intrants.batiment', verbose_name='المبنى')),
                ('bl_fournisseur_poussins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_ouverts', to='achats.blfournisseur', verbose_name='وصل تسليم المورد (كتاكيت)')),
                ('branche', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='core.branche', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur_poussins', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_eleves', to='intrants.fournisseur', verbose_name='مورد الكتاكيت')),
                ('lot_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_enfants', to='elevage.lotelevage', verbose_name='الدفعة الأم (عند التقسيم)')),
            ],
            options={
                'verbose_name': 'دفعة تربية',
                'verbose_name_plural': 'دفعات التربية',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='ParametrageElevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_transfert_poussiniere_jours', models.PositiveIntegerField(default=126, help_text='السن الذي يجب عنده نقل الدفعة من حضانة الكتاكيت إلى حظيرة التربية.', verbose_name='سن النقل من الحضانة (أيام)')),
                ('age_maturite_vente_jours', models.PositiveIntegerField(default=45, help_text='لا يمكن تسجيل سجل إنتاج (ذبح/بيع) لدفعة لم تبلغ هذا السن بعد.', verbose_name='سن النضج الأدنى للبيع/الذبح (أيام)')),
            ],
            options={
                'verbose_name': 'إعدادات التربية',
                'verbose_name_plural': 'إعدادات التربية',
            },
        ),
        migrations.CreateModel(
            name='PeseeEchantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ القياس')),
                ('type_pesee', models.CharField(choices=[('oiseaux', 'طيور'), ('oeufs', 'بيض')], default='oiseaux', max_length=10, verbose_name='نوع القياس')),
                ('nombre_sujets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد العينات')),
                ('poids_total_g', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='الوزن الإجمالي للعينة (غ)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesees_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesees', to='elevage.lotelevage', verbose_name='دفعة التربية')),
            ],
            options={
                'verbose_name': 'وزن عينة',
                'verbose_name_plural': 'أوزان العينات',
                'ordering': ['lot', '-date'],
            },
        ),
        migrations.CreateModel(
            name='TransfertLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateField(verbose_name='تاريخ النقل')),
                ('age_jours_transfert', models.PositiveIntegerField(verbose_name='عمر الدفعة عند النقل (أيام)')),
                ('effectif_transfere', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الطيور المنقولة')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('mode', models.CharField(choices=[('full', 'نقل كامل — الدفعة بأكملها تنتقل'), ('split_new', 'تقسيم — إنشاء دفعة فرعية جديدة في الوجهة'), ('split_merge', 'تقسيم — دمج في دفعة موجودة في الوجهة')], default='full', max_length=15, verbose_name='نوع النقل')),
                ('designation_lot_enfant', models.CharField(blank=True, max_length=255, verbose_name='تسمية الدفعة الفرعية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batiment_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='intrants.batiment', verbose_name='المبنى الجديد')),
                ('batiment_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='intrants.batiment', verbose_name='المبنى الأصلي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_crees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='elevage.lotelevage', verbose_name='دفعة التربية')),
                ('lot_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_recus_fusion', to='elevage.lotelevage', verbose_name='الدفعة الوجهة (عند الدمج)')),
                ('lot_enfant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_origine', to='elevage.lotelevage', verbose_name='الدفعة الفرعية المنشأة')),
            ],
            options={
                'verbose_name': 'نقل دفعة',
                'verbose_name_plural': 'عمليات نقل الدفعات',
                'ordering': ['-date_transfert'],
            },
        ),
        migrations.CreateModel(
            name='RecolteOeufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الجمع')),
                ('nombre_oeufs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد البيض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoltes_oeufs_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes_oeufs', to='elevage.lotelevage', verbose_name='دفعة التربية')),
                ('pesee', models.ForeignKey(blank=True, help_text='قياس وزن عينة من البيض في نفس اليوم تقريباً، لتحديد الجودة.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoltes', to='elevage.peseeechantillon', verbose_name='قياس الوزن المرجعي')),
            ],
            options={
                'verbose_name': 'جمع بيض',
                'verbose_name_plural': 'عمليات جمع البيض',
                'ordering': ['lot', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Mortalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('nombre', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد النافقات')),
                ('cause', models.CharField(blank=True, max_length=255, verbose_name='السبب (إن عُرف)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalites', to='elevage.lotelevage', verbose_name='دفعة التربية')),
            ],
            options={
                'verbose_name': 'نفوق',
                'verbose_name_plural': 'النفوق',
                'ordering': ['lot', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الاستهلاك')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consommations_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('intrant', models.ForeignKey(limit_choices_to={'categorie__consommable_en_lot': True}, on_delete=django.db.models.deletion.PROTECT, related_name='consommations', to='intrants.intrant', verbose_name='المدخل المستهلك')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='elevage.lotelevage', verbose_name='دفعة التربية')),
            ],
            options={
                'verbose_name': 'استهلاك',
                'verbose_name_plural': 'الاستهلاكات',
                'ordering': ['lot', '-date'],
            },
        ),
    ]
