# Generated by Django 6.0.3 on 2026-05-01 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        ('intrants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotElevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='Ex : "Lot Avril 2025 – Bâtiment 1"', max_length=255, verbose_name='Désignation du lot')),
                ('date_ouverture', models.DateField(verbose_name="Date d'ouverture")),
                ('date_fermeture', models.DateField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ouvert', max_length=10, verbose_name='Statut')),
                ('nombre_poussins_initial', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de poussins initial')),
                ('souche', models.CharField(blank=True, help_text='Ex : Ross 308, Cobb 500', max_length=100, verbose_name='Souche (race)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='intrants.batiment', verbose_name='Bâtiment')),
                ('bl_fournisseur_poussins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_ouverts', to='achats.blfournisseur', verbose_name='BL Fournisseur (poussins)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur_poussins', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_eleves', to='intrants.fournisseur', verbose_name='Fournisseur des poussins')),
            ],
            options={
                'verbose_name': "Lot d'élevage",
                'verbose_name_plural': "Lots d'élevage",
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de consommation')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consommations_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('intrant', models.ForeignKey(limit_choices_to={'categorie__consommable_en_lot': True}, on_delete=django.db.models.deletion.PROTECT, related_name='consommations', to='intrants.intrant', verbose_name='Intrant consommé')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='elevage.lotelevage', verbose_name="Lot d'élevage")),
            ],
            options={
                'verbose_name': 'Consommation',
                'verbose_name_plural': 'Consommations',
                'ordering': ['lot', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Mortalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('nombre', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de morts')),
                ('cause', models.CharField(blank=True, max_length=255, verbose_name='Cause (si connue)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalites', to='elevage.lotelevage', verbose_name="Lot d'élevage")),
            ],
            options={
                'verbose_name': 'Mortalité',
                'verbose_name_plural': 'Mortalités',
                'ordering': ['lot', '-date'],
            },
        ),
    ]
