# Generated by Django 6.0.3 on 2026-05-14 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_alter_acomptefournisseur_options_and_more'),
        ('elevage', '0001_initial'),
        ('intrants', '0002_alter_batiment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consommation',
            options={'ordering': ['lot', '-date'], 'verbose_name': 'استهلاك', 'verbose_name_plural': 'الاستهلاكات'},
        ),
        migrations.AlterModelOptions(
            name='lotelevage',
            options={'ordering': ['-date_ouverture'], 'verbose_name': 'دفعة تربية', 'verbose_name_plural': 'دفعات التربية'},
        ),
        migrations.AlterModelOptions(
            name='mortalite',
            options={'ordering': ['lot', '-date'], 'verbose_name': 'نفوق', 'verbose_name_plural': 'النفوق'},
        ),
        migrations.AlterField(
            model_name='consommation',
            name='date',
            field=models.DateField(verbose_name='تاريخ الاستهلاك'),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='intrant',
            field=models.ForeignKey(limit_choices_to={'categorie__consommable_en_lot': True}, on_delete=django.db.models.deletion.PROTECT, related_name='consommations', to='intrants.intrant', verbose_name='المدخل المستهلك'),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='elevage.lotelevage', verbose_name='دفعة التربية'),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='quantite',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='lotelevage',
            name='batiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='intrants.batiment', verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='lotelevage',
            name='bl_fournisseur_poussins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_ouverts', to='achats.blfournisseur', verbose_name='وصل تسليم المورد (كتاكيت)'),
        ),
        migrations.AlterField(
            model_name='lotelevage',
            name='date_fermeture',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإغلاق'),
        ),
        migrations.AlterField(
            model_name='lotelevage',
            name='date_ouverture',
            field=models.DateField(verbose_name='تاريخ الفتح'),
        ),
        migrations.AlterField(
            model_name='lotelevage',
            name='designation',
            field=models.CharField(help_text='مثال: "دفعة أبريل 2025 – المبنى 1"', max_length=255, verbose_name='تسمية الدفعة'),
        ),
        migrations.AlterField(
            model_name='lotelevage',
            name='fournisseur_poussins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_eleves', to='intrants.fournisseur', verbose_name='مورد الكتاكيت'),
        ),
        migrations.AlterField(
            model_name='lotelevage',
            name='nombre_poussins_initial',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الكتاكيت الأولي'),
        ),
        migrations.AlterField(
            model_name='lotelevage',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='lotelevage',
            name='souche',
            field=models.CharField(blank=True, help_text='مثال: Ross 308, Cobb 500', max_length=100, verbose_name='السلالة'),
        ),
        migrations.AlterField(
            model_name='lotelevage',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'مفتوح'), ('ferme', 'مغلق')], default='ouvert', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='mortalite',
            name='cause',
            field=models.CharField(blank=True, max_length=255, verbose_name='السبب (إن عُرف)'),
        ),
        migrations.AlterField(
            model_name='mortalite',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='mortalite',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalites', to='elevage.lotelevage', verbose_name='دفعة التربية'),
        ),
        migrations.AlterField(
            model_name='mortalite',
            name='nombre',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد النافقات'),
        ),
        migrations.AlterField(
            model_name='mortalite',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
    ]
