# Generated by Django 4.2.30 on 2026-07-05 13:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intrants', '0002_unitemesure_alter_intrant_unite_mesure'),
        ('core', '0003_piecejointe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elevage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormuleAliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='اسم التركيبة')),
                ('actif', models.BooleanField(default=True, verbose_name='نشطة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intrant_produit', models.ForeignKey(help_text='العلف الجاهز الذي تُضاف إليه الكمية المصنّعة إلى المخزون.', limit_choices_to={'categorie__code': 'ALIMENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='formules_aliment', to='intrants.intrant', verbose_name='العلف الناتج')),
            ],
            options={
                'verbose_name': 'تركيبة علف',
                'verbose_name_plural': 'تركيبات العلف',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RetraitOeufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ السحب')),
                ('quantite_oeufs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد البيض المسحوب')),
                ('motif', models.CharField(choices=[('client_camion', 'بيع مباشر (شاحنة/زبون)'), ('don', 'هدية / عيّنة مجانية'), ('autre', 'أخرى (فقدان، كسر...)')], default='client_camion', max_length=20, verbose_name='السبب')),
                ('destinataire', models.CharField(blank=True, help_text='اسم الزبون أو المستفيد (اختياري).', max_length=150, verbose_name='الجهة المستفيدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retraits_oeufs', to='core.branche', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_oeufs_enregistres', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_oeufs', to='elevage.lotelevage', verbose_name='الدفعة (اختياري)')),
            ],
            options={
                'verbose_name': 'سحب بيض',
                'verbose_name_plural': 'عمليات سحب البيض',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionAliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ التصنيع/التزويد')),
                ('quantite_produite_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية المصنّعة (كغ)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions_aliment', to='core.branche', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_aliment_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('formule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='elevage.formulealiment', verbose_name='التركيبة (اختياري)')),
                ('intrant_produit', models.ForeignKey(limit_choices_to={'categorie__code': 'ALIMENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='productions_aliment', to='intrants.intrant', verbose_name='العلف المصنّع')),
            ],
            options={
                'verbose_name': 'تصنيع/تزويد علف',
                'verbose_name_plural': 'عمليات تصنيع العلف',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FormuleAlimentLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proportion_kg', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='كغ لكل 100 كغ علف ناتج')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='elevage.formulealiment', verbose_name='التركيبة')),
                ('intrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_formule_aliment', to='intrants.intrant', verbose_name='المدخل (مكوّن)')),
            ],
            options={
                'verbose_name': 'مكوّن تركيبة',
                'verbose_name_plural': 'مكوّنات التركيبة',
                'ordering': ['formule', '-proportion_kg'],
                'unique_together': {('formule', 'intrant')},
            },
        ),
    ]
