# Generated by Django 4.2.30 on 2026-07-05 14:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0002_formulealiment_retraitoeufs_productionaliment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionaliment',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='تكلفة الكيلوغرام الواحد من هذا التزويد. عند تركه 0 (الحالة الافتراضية)، لا يُعاد حساب متوسط سعر مخزون هذا العلف — يبقى PMP كما هو. هذا هو الحقل الأكثر استعمالاً عند الإضافة المباشرة (بدون تركيبة). عند اختيار تركيبة، يمكن تركه 0 لأن التكلفة تُشتق تلقائياً من أسعار مكوّناتها الحالية في المخزون (انظر elevage.signals.production_aliment_post_save).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة (د.ج/كغ) — اختياري'),
        ),
    ]
