# Generated by Django 6.0.3 on 2026-06-20 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0002_alter_consommation_options_alter_lotelevage_options_and_more'),
        ('intrants', '0003_batiment_categorie_stockage_batiment_type_batiment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrageElevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_transfert_poussiniere_jours', models.PositiveIntegerField(default=126, help_text='السن الذي يجب عنده نقل الدفعة من حضانة الكتاكيت إلى حظيرة التربية.', verbose_name='سن النقل من الحضانة (أيام)')),
                ('age_maturite_vente_jours', models.PositiveIntegerField(default=45, help_text='لا يمكن تسجيل سجل إنتاج (ذبح/بيع) لدفعة لم تبلغ هذا السن بعد.', verbose_name='سن النضج الأدنى للبيع/الذبح (أيام)')),
            ],
            options={
                'verbose_name': 'إعدادات التربية',
                'verbose_name_plural': 'إعدادات التربية',
            },
        ),
        migrations.CreateModel(
            name='PeseeEchantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ القياس')),
                ('type_pesee', models.CharField(choices=[('oiseaux', 'طيور'), ('oeufs', 'بيض')], default='oiseaux', max_length=10, verbose_name='نوع القياس')),
                ('nombre_sujets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد العينات')),
                ('poids_total_g', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='الوزن الإجمالي للعينة (غ)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesees_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesees', to='elevage.lotelevage', verbose_name='دفعة التربية')),
            ],
            options={
                'verbose_name': 'وزن عينة',
                'verbose_name_plural': 'أوزان العينات',
                'ordering': ['lot', '-date'],
            },
        ),
        migrations.CreateModel(
            name='RecolteOeufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الجمع')),
                ('nombre_oeufs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد البيض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoltes_oeufs_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes_oeufs', to='elevage.lotelevage', verbose_name='دفعة التربية')),
                ('pesee', models.ForeignKey(blank=True, help_text='قياس وزن عينة من البيض في نفس اليوم تقريباً، لتحديد الجودة.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoltes', to='elevage.peseeechantillon', verbose_name='قياس الوزن المرجعي')),
            ],
            options={
                'verbose_name': 'جمع بيض',
                'verbose_name_plural': 'عمليات جمع البيض',
                'ordering': ['lot', '-date'],
            },
        ),
        migrations.CreateModel(
            name='TransfertLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateField(verbose_name='تاريخ النقل')),
                ('age_jours_transfert', models.PositiveIntegerField(verbose_name='عمر الدفعة عند النقل (أيام)')),
                ('effectif_transfere', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الطيور المنقولة')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batiment_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='intrants.batiment', verbose_name='المبنى الجديد')),
                ('batiment_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='intrants.batiment', verbose_name='المبنى الأصلي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_crees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='elevage.lotelevage', verbose_name='دفعة التربية')),
            ],
            options={
                'verbose_name': 'نقل دفعة',
                'verbose_name_plural': 'عمليات نقل الدفعات',
                'ordering': ['-date_transfert'],
            },
        ),
    ]
