# Generated by Django 4.2.30 on 2026-07-05 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_typeclient_alter_client_type_client'),
        ('elevage', '0003_productionaliment_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='retraitoeufs',
            name='bl_genere',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrait_oeufs_origine', to='clients.blclient', verbose_name='وصل التسليم المُنشأ'),
        ),
        migrations.AddField(
            model_name='retraitoeufs',
            name='client',
            field=models.ForeignKey(blank=True, help_text='اختر عميلاً مسجلاً لإنشاء وصل تسليم (BL) رسمي بهذه الكمية تلقائياً.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retraits_oeufs', to='clients.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='retraitoeufs',
            name='destinataire',
            field=models.CharField(blank=True, help_text='اسم الزبون أو المستفيد إن لم يكن عميلاً مسجلاً (اختياري).', max_length=150, verbose_name='الجهة المستفيدة'),
        ),
    ]
