# Generated by Django 6.0.3 on 2026-06-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0003_parametrageelevage_peseeechantillon_recolteoeufs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotelevage',
            name='lot_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_enfants', to='elevage.lotelevage', verbose_name='الدفعة الأم (عند التقسيم)'),
        ),
        migrations.AddField(
            model_name='transfertlot',
            name='designation_lot_enfant',
            field=models.CharField(blank=True, max_length=255, verbose_name='تسمية الدفعة الفرعية'),
        ),
        migrations.AddField(
            model_name='transfertlot',
            name='lot_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_recus_fusion', to='elevage.lotelevage', verbose_name='الدفعة الوجهة (عند الدمج)'),
        ),
        migrations.AddField(
            model_name='transfertlot',
            name='lot_enfant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_origine', to='elevage.lotelevage', verbose_name='الدفعة الفرعية المنشأة'),
        ),
        migrations.AddField(
            model_name='transfertlot',
            name='mode',
            field=models.CharField(choices=[('full', 'نقل كامل — الدفعة بأكملها تنتقل'), ('split_new', 'تقسيم — إنشاء دفعة فرعية جديدة في الوجهة'), ('split_merge', 'تقسيم — دمج في دفعة موجودة في الوجهة')], default='full', max_length=15, verbose_name='نوع النقل'),
        ),
    ]
