# Generated by Django 4.2.30 on 2026-07-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_detteemploye_jourferie_bulletinpaie_jours_feries_and_more'),
        ('elevage', '0004_retraitoeufs_bl_genere_retraitoeufs_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionaliment',
            name='depense_paiement',
            field=models.ForeignKey(blank=True, help_text='يُملأ تلقائياً عند تجميع هذه العملية ضمن دفعة أجرة تصنيع علف (انظر: دفع تصنيع العلف).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_aliment_payees', to='depenses.depense', verbose_name='مصروف دفع اليد العاملة المرتبط'),
        ),
    ]
