# Generated by Django 4.2.30 on 2026-07-09 10:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_detteemploye_jourferie_bulletinpaie_jours_feries_and_more'),
        ('elevage', '0005_productionaliment_depense_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='depense_paiement',
            field=models.ForeignKey(blank=True, help_text='يُملأ تلقائياً عند تجميع هذا الاستهلاك ضمن دفعة أجرة طبيب/فريق بيطري (انظر: دفع أجرة الأدوية).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consommations_medicament_payees', to='depenses.depense', verbose_name='مصروف دفع أجرة الطبيب/الفريق المرتبط'),
        ),
        migrations.AddField(
            model_name='consommation',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='سعر الوحدة الواحدة من الدواء/اللقاح — اختياري. أدخله هنا عند معرفة السعر فوراً (يُنشئ مصروفاً تلقائياً). اتركه 0 لتجميع هذا الاستهلاك لاحقاً ضمن دفعة أجرة طبيب/فريق بيطري واحدة (انظر: استهلاكات الأدوية ← دفع أجرة).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة (اختياري)'),
        ),
    ]
