# Generated by Django 4.2.30 on 2026-07-09 20:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0006_consommation_depense_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionaliment',
            name='cout_facon_impute',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مجموع أجرة التصنيع المُعترف بها كتكلفة حتى الآن، بنسبة الكمية المستهلكة فعلياً من هذه الدفعة × prix_facon_unitaire. يتحدّث مع كل استهلاك جديد، وبأثر رجعي عند دفع الأجرة إن كان جزء من الدفعة قد استُهلك من قبل — انظر signals.py و views._recognize_facon_cost_for_batch.', max_digits=14, verbose_name='تكلفة أجرة التصنيع المحمّلة تراكمياً'),
        ),
        migrations.AddField(
            model_name='productionaliment',
            name='prix_facon_unitaire',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='يُملأ تلقائياً بسعر الوحدة المُدخل عند تجميع هذه الدفعة ضمن دفع أجرة تصنيع (انظر production_aliment_paiement_create). يبقى 0 للدفعات المباشرة (بدون تركيبة) أو التي لم تُدفع أجرتها بعد.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='أجرة التصنيع للكيلوغرام (د.ج/كغ)'),
        ),
        migrations.AddField(
            model_name='productionaliment',
            name='quantite_restante_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='تُهيّأ تلقائياً بقيمة الكمية المصنّعة عند الإنشاء، ثم تُخصم تدريجياً مع كل استهلاك يُخصَّص لهذه الدفعة تحديداً (FIFO حسب التاريخ). تُستعمل لتوزيع أجرة التصنيع تناسبياً مع نسبة الاستهلاك.', max_digits=12, verbose_name='الكمية المتبقية من هذه الدفعة (كغ)'),
        ),
        migrations.CreateModel(
            name='ConsommationAlimentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية المأخوذة من هذه الدفعة (كغ)')),
                ('cout_facon_alloue', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='quantite_kg × production.prix_facon_unitaire وقت التخصيص. تبقى 0 إن لم تكن أجرة الدفعة معروفة بعد؛ تُحدَّث بأثر رجعي عند دفع أجرة التصنيع (انظر views._recognize_facon_cost_for_batch).', max_digits=14, verbose_name='حصة أجرة التصنيع المخصّصة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consommation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_batch', to='elevage.consommation', verbose_name='الاستهلاك')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations_consommees', to='elevage.productionaliment', verbose_name='دفعة الإنتاج')),
            ],
            options={
                'verbose_name': 'تخصيص دفعة علف مستهلكة',
                'verbose_name_plural': 'تخصيصات دفعات العلف المستهلكة',
                'ordering': ['consommation', 'production__date'],
                'unique_together': {('consommation', 'production')},
            },
        ),
    ]
