# Generated by Django 4.2.30 on 2026-07-10 15:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0007_productionaliment_cout_facon_impute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertlot',
            name='cout_herite_alloue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='التكلفة الموروثة المخصصة لهذه الطيور (د.ج) — بدون الرواتب'),
        ),
        migrations.AddField(
            model_name='transfertlot',
            name='part_effectif_snapshot',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9, verbose_name='نسبة الطيور المنقولة من مجموع الناجين وقت النقل'),
        ),
    ]
