# Generated by Django 4.2.30 on 2026-07-10 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_prixmarche_poids_reference_kg'),
        ('elevage', '0008_transfertlot_cout_herite_alloue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peseeechantillon',
            name='estimation_prix_plateau',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='تقدير المدير لسعر الصينية بناءً على الوزن الفعلي — يُقترح تلقائياً تناسبياً مع سعر السوق المرجعي، وقابل للتعديل من طرف المدير فقط.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تقديري لسعر الصينية (د.ج)'),
        ),
        migrations.AddField(
            model_name='peseeechantillon',
            name='prix_marche',
            field=models.ForeignKey(blank=True, help_text='سعر السوق المعتمد كمرجع لتقدير قيمة صينية هذه العينة.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesees_oeufs', to='clients.prixmarche', verbose_name='سعر السوق المرجعي (صينية)'),
        ),
    ]
