# Generated by Django 4.2.30 on 2026-07-15 19:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0009_peseeechantillon_estimation_prix_plateau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulealiment',
            name='base_kg',
            field=models.PositiveIntegerField(choices=[(1, '1 كغ (لكل وحدة واحدة)'), (10, '10 كغ'), (100, '100 كغ'), (1000, '1000 كغ (طن)')], default=100, help_text='حجم الدفعة المستعمل فقط لإدخال/عرض كميات المكوّنات أدناه (مثلاً أدخل المكوّنات كما لو كنت تُصنّع 100 كغ). لا يُغيّر هذا أبداً النسب المخزّنة فعلياً — تبقى دائماً لكل كغ واحد من العلف الناتج.', verbose_name='وحدة إدخال المكوّنات (وضعية الإنتاج)'),
        ),
        migrations.AddField(
            model_name='formulealimentligne',
            name='est_complement',
            field=models.BooleanField(default=False, help_text='عند التفعيل، تُحسب كمية هذا المكوّن تلقائياً لتكملة الدفعة إلى 100% من العلف الناتج بدل إدخالها يدوياً. يُسمح بمكوّن تكميلي واحد فقط لكل تركيبة.', verbose_name='مكوّن تكميلي (يملأ الباقي تلقائياً)'),
        ),
        migrations.AlterField(
            model_name='formulealimentligne',
            name='proportion_kg',
            field=models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))], verbose_name='كغ لكل كغ واحد من العلف الناتج'),
        ),
    ]
