# Generated by Django 4.2.30 on 2026-06-30 22:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('intrants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='مرجع وصل التسليم')),
                ('date_bl', models.DateField(verbose_name='تاريخ وصل التسليم / تاريخ التفويض')),
                ('reference_fournisseur', models.CharField(blank=True, help_text='للتفويض: رقم أمر الشراء عند المورد (مثال: C632/15).', max_length=100, verbose_name='مرجع المورد')),
                ('type_document', models.CharField(choices=[('bl_classique', 'وصل تسليم كلاسيكي'), ('autorisation_acces', 'تفويض وصول (ONAB وما شابه)')], default='bl_classique', max_length=25, verbose_name='نوع الوثيقة')),
                ('statut', models.CharField(choices=[('autorise', 'مفوَّض (في انتظار الاستلام)'), ('brouillon', 'مسودة'), ('recu', 'مستلم'), ('facture', 'مفوتر'), ('litige', 'في نزاع')], default='brouillon', max_length=20, verbose_name='الحالة')),
                ('notes_reception', models.TextField(blank=True, verbose_name='ملاحظات الاستلام')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='bl_fournisseur/%Y/%m/', verbose_name='مرفق (PDF/JPG/PNG)')),
                ('numero_autorisation', models.CharField(blank=True, help_text='الرقم الصادر من المورد (مثال: 27196 لـ ONAB).', max_length=50, verbose_name='رقم التفويض')),
                ('date_expiration_autorisation', models.DateField(blank=True, help_text='يجب استلام البضاعة قبل هذا التاريخ (BR-BLF-05).', null=True, verbose_name='تاريخ انتهاء التفويض')),
                ('nom_chauffeur', models.CharField(blank=True, max_length=150, verbose_name='اسم السائق')),
                ('matricule_camion', models.CharField(blank=True, max_length=50, verbose_name='رقم تسجيل الشاحنة')),
                ('numero_permis', models.CharField(blank=True, max_length=50, verbose_name='رقم رخصة القيادة')),
                ('portail_entree', models.CharField(blank=True, max_length=50, verbose_name='بوابة الدخول')),
                ('portail_sortie', models.CharField(blank=True, help_text='يُملأ عند خروج الشاحنة محملة — يؤكد اكتمال الاستلام الفعلي.', max_length=50, verbose_name='بوابة الخروج')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bls_fournisseur', to='core.branche', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bls_fournisseur_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bls_fournisseur', to='intrants.fournisseur', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'وصل تسليم المورد',
                'verbose_name_plural': 'وصولات تسليم المورد',
                'ordering': ['-date_bl', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReglementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reglement', models.DateField(verbose_name='تاريخ التسوية')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ (د.ج)')),
                ('mode_paiement', models.CharField(choices=[('especes', 'نقداً'), ('cheque', 'شيك'), ('virement', 'تحويل بنكي'), ('autre', 'أخرى')], default='especes', max_length=20, verbose_name='طريقة الدفع')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='المرجع (رقم الشيك / التحويل)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements_fournisseur', to='core.branche', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglements_fournisseur_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='intrants.fournisseur', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'تسوية المورد',
                'verbose_name_plural': 'تسويات الموردين',
                'ordering': ['-date_reglement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='مرجع الفاتورة')),
                ('date_facture', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('type_facture', models.CharField(choices=[('marchandises', 'بضائع'), ('service', 'خدمة')], default='marchandises', max_length=20, verbose_name='نوع الفاتورة')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ الإجمالي (د.ج)')),
                ('montant_regle', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المسدد (د.ج)')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المتبقي (د.ج)')),
                ('statut', models.CharField(choices=[('non_paye', 'غير مدفوعة'), ('partiellement_paye', 'مدفوعة جزئياً'), ('paye', 'مدفوعة'), ('en_litige', 'في نزاع')], default='non_paye', max_length=25, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bls', models.ManyToManyField(blank=True, related_name='factures', to='achats.blfournisseur', verbose_name='وصولات التسليم المضمنة')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_fournisseur', to='core.branche', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_fournisseur_creees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_fournisseur', to='intrants.fournisseur', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'فاتورة المورد',
                'verbose_name_plural': 'فواتير الموردين',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='BLFournisseurLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية')),
                ('prix_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة (د.ج)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.blfournisseur', verbose_name='وصل تسليم المورد')),
                ('intrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bl_fournisseur', to='intrants.intrant', verbose_name='المدخل')),
            ],
            options={
                'verbose_name': 'سطر وصل تسليم المورد',
                'verbose_name_plural': 'أسطر وصل تسليم المورد',
            },
        ),
        migrations.CreateModel(
            name='AllocationReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_alloue', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المخصص (د.ج)')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='achats.facturefournisseur', verbose_name='الفاتورة')),
                ('reglement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='achats.reglementfournisseur', verbose_name='التسوية')),
            ],
            options={
                'verbose_name': 'تخصيص التسوية',
                'verbose_name_plural': 'تخصيصات التسويات',
            },
        ),
        migrations.CreateModel(
            name='AcompteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ (د.ج)')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('utilise', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acomptes_fournisseur', to='core.branche', verbose_name='الفرع')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acomptes', to='intrants.fournisseur', verbose_name='المورد')),
                ('reglement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acompte', to='achats.reglementfournisseur', verbose_name='التسوية المصدر')),
            ],
            options={
                'verbose_name': 'دفعة مقدمة للمورد',
                'verbose_name_plural': 'دفعات مقدمة للموردين',
                'ordering': ['-date'],
            },
        ),
    ]
