# Generated by Django 6.0.3 on 2026-05-01 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intrants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BLFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence BL')),
                ('date_bl', models.DateField(verbose_name='Date du BL')),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Référence fournisseur')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('recu', 'Reçu'), ('facture', 'Facturé'), ('litige', 'En litige')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('notes_reception', models.TextField(blank=True, verbose_name='Notes de réception')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='bl_fournisseur/%Y/%m/', verbose_name='Pièce jointe (PDF/JPG/PNG)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bls_fournisseur_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bls_fournisseur', to='intrants.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'BL Fournisseur',
                'verbose_name_plural': 'BL Fournisseurs',
                'ordering': ['-date_bl', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BLFournisseurLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire (DZD)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.blfournisseur', verbose_name='BL Fournisseur')),
                ('intrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bl_fournisseur', to='intrants.intrant', verbose_name='Intrant')),
            ],
            options={
                'verbose_name': 'Ligne BL Fournisseur',
                'verbose_name_plural': 'Lignes BL Fournisseur',
            },
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence facture')),
                ('date_facture', models.DateField(verbose_name='Date de la facture')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('type_facture', models.CharField(choices=[('marchandises', 'Marchandises'), ('service', 'Service')], default='marchandises', max_length=20, verbose_name='Type de facture')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total (DZD)')),
                ('montant_regle', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant réglé (DZD)')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Reste à payer (DZD)')),
                ('statut', models.CharField(choices=[('non_paye', 'Non payée'), ('partiellement_paye', 'Partiellement payée'), ('paye', 'Payée'), ('en_litige', 'En litige')], default='non_paye', max_length=25, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bls', models.ManyToManyField(blank=True, related_name='factures', to='achats.blfournisseur', verbose_name='BL inclus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_fournisseur_creees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_fournisseur', to='intrants.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Facture Fournisseur',
                'verbose_name_plural': 'Factures Fournisseurs',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='ReglementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reglement', models.DateField(verbose_name='Date du règlement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant (DZD)')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence (n° chèque / virement)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglements_fournisseur_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='intrants.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Règlement Fournisseur',
                'verbose_name_plural': 'Règlements Fournisseurs',
                'ordering': ['-date_reglement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_alloue', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant alloué (DZD)')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='achats.facturefournisseur', verbose_name='Facture')),
                ('reglement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='achats.reglementfournisseur', verbose_name='Règlement')),
            ],
            options={
                'verbose_name': 'Allocation Règlement',
                'verbose_name_plural': 'Allocations Règlements',
            },
        ),
        migrations.CreateModel(
            name='AcompteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant (DZD)')),
                ('date', models.DateField(verbose_name='Date')),
                ('utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acomptes', to='intrants.fournisseur', verbose_name='Fournisseur')),
                ('reglement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acompte', to='achats.reglementfournisseur', verbose_name='Règlement source')),
            ],
            options={
                'verbose_name': 'Acompte Fournisseur',
                'verbose_name_plural': 'Acomptes Fournisseurs',
                'ordering': ['-date'],
            },
        ),
    ]
