# Generated by Django 6.0.3 on 2026-05-14 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
        ('intrants', '0002_alter_batiment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acomptefournisseur',
            options={'ordering': ['-date'], 'verbose_name': 'دفعة مقدمة للمورد', 'verbose_name_plural': 'دفعات مقدمة للموردين'},
        ),
        migrations.AlterModelOptions(
            name='allocationreglement',
            options={'verbose_name': 'تخصيص التسوية', 'verbose_name_plural': 'تخصيصات التسويات'},
        ),
        migrations.AlterModelOptions(
            name='blfournisseur',
            options={'ordering': ['-date_bl', '-created_at'], 'verbose_name': 'وصل تسليم المورد', 'verbose_name_plural': 'وصولات تسليم المورد'},
        ),
        migrations.AlterModelOptions(
            name='blfournisseurligne',
            options={'verbose_name': 'سطر وصل تسليم المورد', 'verbose_name_plural': 'أسطر وصل تسليم المورد'},
        ),
        migrations.AlterModelOptions(
            name='facturefournisseur',
            options={'ordering': ['-date_facture'], 'verbose_name': 'فاتورة المورد', 'verbose_name_plural': 'فواتير الموردين'},
        ),
        migrations.AlterModelOptions(
            name='reglementfournisseur',
            options={'ordering': ['-date_reglement', '-created_at'], 'verbose_name': 'تسوية المورد', 'verbose_name_plural': 'تسويات الموردين'},
        ),
        migrations.AlterField(
            model_name='acomptefournisseur',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='acomptefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acomptes', to='intrants.fournisseur', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='acomptefournisseur',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ (د.ج)'),
        ),
        migrations.AlterField(
            model_name='acomptefournisseur',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='acomptefournisseur',
            name='reglement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acompte', to='achats.reglementfournisseur', verbose_name='التسوية المصدر'),
        ),
        migrations.AlterField(
            model_name='acomptefournisseur',
            name='utilise',
            field=models.BooleanField(default=False, verbose_name='مستخدم'),
        ),
        migrations.AlterField(
            model_name='allocationreglement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='achats.facturefournisseur', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='allocationreglement',
            name='montant_alloue',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المخصص (د.ج)'),
        ),
        migrations.AlterField(
            model_name='allocationreglement',
            name='reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='achats.reglementfournisseur', verbose_name='التسوية'),
        ),
        migrations.AlterField(
            model_name='blfournisseur',
            name='date_bl',
            field=models.DateField(verbose_name='تاريخ وصل التسليم'),
        ),
        migrations.AlterField(
            model_name='blfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bls_fournisseur', to='intrants.fournisseur', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='blfournisseur',
            name='notes_reception',
            field=models.TextField(blank=True, verbose_name='ملاحظات الاستلام'),
        ),
        migrations.AlterField(
            model_name='blfournisseur',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='bl_fournisseur/%Y/%m/', verbose_name='مرفق (PDF/JPG/PNG)'),
        ),
        migrations.AlterField(
            model_name='blfournisseur',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='مرجع وصل التسليم'),
        ),
        migrations.AlterField(
            model_name='blfournisseur',
            name='reference_fournisseur',
            field=models.CharField(blank=True, max_length=100, verbose_name='مرجع المورد'),
        ),
        migrations.AlterField(
            model_name='blfournisseur',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'مسودة'), ('recu', 'مستلم'), ('facture', 'مفوتر'), ('litige', 'في نزاع')], default='brouillon', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='blfournisseurligne',
            name='bl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.blfournisseur', verbose_name='وصل تسليم المورد'),
        ),
        migrations.AlterField(
            model_name='blfournisseurligne',
            name='intrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bl_fournisseur', to='intrants.intrant', verbose_name='المدخل'),
        ),
        migrations.AlterField(
            model_name='blfournisseurligne',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='blfournisseurligne',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة (د.ج)'),
        ),
        migrations.AlterField(
            model_name='blfournisseurligne',
            name='quantite',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='bls',
            field=models.ManyToManyField(blank=True, related_name='factures', to='achats.blfournisseur', verbose_name='وصولات التسليم المضمنة'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='date_facture',
            field=models.DateField(verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_fournisseur', to='intrants.fournisseur', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='montant_regle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المسدد (د.ج)'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ الإجمالي (د.ج)'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='مرجع الفاتورة'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المتبقي (د.ج)'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='statut',
            field=models.CharField(choices=[('non_paye', 'غير مدفوعة'), ('partiellement_paye', 'مدفوعة جزئياً'), ('paye', 'مدفوعة'), ('en_litige', 'في نزاع')], default='non_paye', max_length=25, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='type_facture',
            field=models.CharField(choices=[('marchandises', 'بضائع'), ('service', 'خدمة')], default='marchandises', max_length=20, verbose_name='نوع الفاتورة'),
        ),
        migrations.AlterField(
            model_name='reglementfournisseur',
            name='date_reglement',
            field=models.DateField(verbose_name='تاريخ التسوية'),
        ),
        migrations.AlterField(
            model_name='reglementfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='intrants.fournisseur', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='reglementfournisseur',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'نقداً'), ('cheque', 'شيك'), ('virement', 'تحويل بنكي'), ('autre', 'أخرى')], default='especes', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='reglementfournisseur',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ (د.ج)'),
        ),
        migrations.AlterField(
            model_name='reglementfournisseur',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='reglementfournisseur',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100, verbose_name='المرجع (رقم الشيك / التحويل)'),
        ),
    ]
