# Generated by Django 6.0.3 on 2026-06-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_alter_acomptefournisseur_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blfournisseur',
            name='date_expiration_autorisation',
            field=models.DateField(blank=True, help_text='يجب استلام البضاعة قبل هذا التاريخ (BR-BLF-05).', null=True, verbose_name='تاريخ انتهاء التفويض'),
        ),
        migrations.AddField(
            model_name='blfournisseur',
            name='matricule_camion',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم تسجيل الشاحنة'),
        ),
        migrations.AddField(
            model_name='blfournisseur',
            name='nom_chauffeur',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم السائق'),
        ),
        migrations.AddField(
            model_name='blfournisseur',
            name='numero_autorisation',
            field=models.CharField(blank=True, help_text='الرقم الصادر من المورد (مثال: 27196 لـ ONAB).', max_length=50, verbose_name='رقم التفويض'),
        ),
        migrations.AddField(
            model_name='blfournisseur',
            name='numero_permis',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم رخصة القيادة'),
        ),
        migrations.AddField(
            model_name='blfournisseur',
            name='portail_entree',
            field=models.CharField(blank=True, max_length=50, verbose_name='بوابة الدخول'),
        ),
        migrations.AddField(
            model_name='blfournisseur',
            name='portail_sortie',
            field=models.CharField(blank=True, help_text='يُملأ عند خروج الشاحنة محملة — يؤكد اكتمال الاستلام الفعلي.', max_length=50, verbose_name='بوابة الخروج'),
        ),
        migrations.AddField(
            model_name='blfournisseur',
            name='type_document',
            field=models.CharField(choices=[('bl_classique', 'وصل تسليم كلاسيكي'), ('autorisation_acces', 'تفويض وصول (ONAB وما شابه)')], default='bl_classique', max_length=25, verbose_name='نوع الوثيقة'),
        ),
        migrations.AlterField(
            model_name='blfournisseur',
            name='date_bl',
            field=models.DateField(verbose_name='تاريخ وصل التسليم / تاريخ التفويض'),
        ),
        migrations.AlterField(
            model_name='blfournisseur',
            name='reference_fournisseur',
            field=models.CharField(blank=True, help_text='للتفويض: رقم أمر الشراء عند المورد (مثال: C632/15).', max_length=100, verbose_name='مرجع المورد'),
        ),
        migrations.AlterField(
            model_name='blfournisseur',
            name='statut',
            field=models.CharField(choices=[('autorise', 'مفوَّض (في انتظار الاستلام)'), ('brouillon', 'مسودة'), ('recu', 'مستلم'), ('facture', 'مفوتر'), ('litige', 'في نزاع')], default='brouillon', max_length=20, verbose_name='الحالة'),
        ),
    ]
