# Generated by Django 4.2.30 on 2026-07-06 08:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_remove_blfournisseur_piece_jointe'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomptefournisseur',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المتبقي (د.ج)'),
        ),
        migrations.AlterField(
            model_name='acomptefournisseur',
            name='utilise',
            field=models.BooleanField(default=False, verbose_name='مستخدمة بالكامل'),
        ),
        migrations.CreateModel(
            name='AllocationAcompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_alloue', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المخصص (د.ج)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acompte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='achats.acomptefournisseur', verbose_name='الدفعة المقدمة')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations_acompte', to='achats.facturefournisseur', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'تخصيص الدفعة المقدمة',
                'verbose_name_plural': 'تخصيصات الدفعات المقدمة',
            },
        ),
    ]
