# Generated by Django 6.0.3 on 2026-05-01 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elevage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitFini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('type_produit', models.CharField(choices=[('volaille_vivante', 'Volaille vivante'), ('carcasse', 'Carcasse entière'), ('decoupe', 'Découpe'), ('abats', 'Abats'), ('oeufs', 'Œufs'), ('autre', 'Autre')], default='volaille_vivante', max_length=30, verbose_name='Type de produit')),
                ('unite_mesure', models.CharField(choices=[('unite', 'Unité / Tête'), ('kg', 'Kilogramme (kg)'), ('plateau', 'Plateau'), ('caisse', 'Caisse'), ('paquet', 'Paquet')], default='unite', max_length=20, verbose_name='Unité de mesure')),
                ('prix_vente_defaut', models.DecimalField(decimal_places=2, default=0, help_text='Pré-rempli sur les lignes BL client — modifiable.', max_digits=12, verbose_name='Prix de vente par défaut (DZD)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit fini',
                'verbose_name_plural': 'Produits finis',
                'ordering': ['type_produit', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_production', models.DateField(verbose_name='Date de production / abattage')),
                ('nombre_oiseaux_abattus', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="Nombre d'oiseaux abattus / récoltés")),
                ('poids_total_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Poids total (kg)')),
                ('poids_moyen_kg', models.DecimalField(decimal_places=3, default=0, help_text='Auto-calculé si poids_total fourni.', max_digits=8, verbose_name='Poids moyen par oiseau (kg)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='elevage.lotelevage', verbose_name="Lot d'élevage")),
            ],
            options={
                'verbose_name': 'Enregistrement de production',
                'verbose_name_plural': 'Enregistrements de production',
                'ordering': ['-date_production'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité produite')),
                ('poids_unitaire_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Poids unitaire (kg)')),
                ('cout_unitaire_estime', models.DecimalField(decimal_places=4, default=0, help_text='Alloué depuis le coût total du lot.', max_digits=12, verbose_name='Coût unitaire estimé (DZD)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='production.productionrecord', verbose_name='Enregistrement de production')),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_production', to='production.produitfini', verbose_name='Produit fini')),
            ],
            options={
                'verbose_name': 'Ligne de production',
                'verbose_name_plural': 'Lignes de production',
            },
        ),
    ]
