# Generated by Django 4.2.30 on 2026-06-30 22:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intrants', '0001_initial'),
        ('elevage', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitFini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='التسمية')),
                ('type_produit', models.CharField(choices=[('volaille_vivante', 'دواجن حية'), ('carcasse', 'ذبيحة كاملة'), ('decoupe', 'قطع'), ('abats', 'مخلفات الذبح'), ('oeufs', 'بيض'), ('fertilisant', 'سماد معالج'), ('autre', 'أخرى')], default='volaille_vivante', max_length=30, verbose_name='نوع المنتج')),
                ('unite_mesure', models.CharField(choices=[('unite', 'وحدة / رأس'), ('kg', 'كيلوغرام (كغ)'), ('plateau', 'صينية'), ('caisse', 'صندوق'), ('paquet', 'طرد')], default='unite', max_length=20, verbose_name='وحدة القياس')),
                ('prix_vente_defaut', models.DecimalField(decimal_places=2, default=0, help_text='يُملأ مسبقاً في أسطر وصل تسليم العميل — قابل للتعديل.', max_digits=12, verbose_name='سعر البيع الافتراضي (د.ج)')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'منتج نهائي',
                'verbose_name_plural': 'المنتجات النهائية',
                'ordering': ['type_produit', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='TraitementFertilisant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_traitement', models.DateField(verbose_name='تاريخ المعالجة')),
                ('methode', models.CharField(blank=True, help_text='مثال: تجفيف، تخمير، معالجة حرارية...', max_length=255, verbose_name='طريقة المعالجة')),
                ('quantite_obtenue_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية النهائية المتحصل عليها (كغ)')),
                ('cout_unitaire_estime', models.DecimalField(decimal_places=4, default=0, help_text='تُستخدم لحساب متوسط تكلفة الإنتاج عبر المعادلة الموزونة.', max_digits=12, verbose_name='التكلفة الوحدوية المقدرة (د.ج)')),
                ('statut', models.CharField(choices=[('brouillon', 'مسودة'), ('valide', 'معتمد')], default='brouillon', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traitements_fertilisant', to='core.branche', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements_fertilisant_enregistres', to=settings.AUTH_USER_MODEL)),
                ('produit_fini', models.ForeignKey(limit_choices_to={'type_produit': 'fertilisant'}, on_delete=django.db.models.deletion.PROTECT, related_name='traitements_fertilisant', to='production.produitfini', verbose_name='المنتج النهائي (السماد)')),
            ],
            options={
                'verbose_name': 'معالجة سماد',
                'verbose_name_plural': 'عمليات معالجة السماد',
                'ordering': ['-date_traitement'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_production', models.DateField(verbose_name='تاريخ الإنتاج / الذبح')),
                ('nombre_oiseaux_abattus', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الطيور المذبوحة / المحصودة')),
                ('poids_total_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن الإجمالي (كغ)')),
                ('poids_moyen_kg', models.DecimalField(decimal_places=3, default=0, help_text='يُحسب تلقائياً إذا تم إدخال الوزن الإجمالي.', max_digits=8, verbose_name='متوسط الوزن لكل طير (كغ)')),
                ('statut', models.CharField(choices=[('brouillon', 'مسودة'), ('valide', 'معتمد')], default='brouillon', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branche', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='core.branche', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='elevage.lotelevage', verbose_name='دفعة التربية')),
            ],
            options={
                'verbose_name': 'سجل إنتاج',
                'verbose_name_plural': 'سجلات الإنتاج',
                'ordering': ['-date_production'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية المنتجة')),
                ('poids_unitaire_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='الوزن لكل وحدة (كغ)')),
                ('cout_unitaire_estime', models.DecimalField(decimal_places=4, default=0, help_text='مخصص من التكلفة الإجمالية للدفعة.', max_digits=12, verbose_name='التكلفة الوحدوية المقدرة (د.ج)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='production.productionrecord', verbose_name='سجل الإنتاج')),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_production', to='production.produitfini', verbose_name='المنتج النهائي')),
            ],
            options={
                'verbose_name': 'سطر إنتاج',
                'verbose_name_plural': 'أسطر الإنتاج',
            },
        ),
        migrations.CreateModel(
            name='CollecteFertilisant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collecte', models.DateField(verbose_name='تاريخ الجمع')),
                ('quantite_brute_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية الخام (كغ)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectes_fertilisant', to='intrants.batiment', verbose_name='المبنى')),
                ('branche', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='collectes_fertilisant', to='core.branche', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_fertilisant_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('traitement', models.ForeignKey(blank=True, help_text='يُملأ عند تخصيص هذه الكمية الخام لعملية معالجة (دفعة).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes', to='production.traitementfertilisant', verbose_name='عملية المعالجة')),
            ],
            options={
                'verbose_name': 'جمع سماد خام',
                'verbose_name_plural': 'عمليات جمع السماد الخام',
                'ordering': ['-date_collecte'],
            },
        ),
    ]
