# Generated by Django 4.2.30 on 2026-07-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intrants', '0002_unitemesure_alter_intrant_unite_mesure'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduitFini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مفتاح ثابت: VOLAILLE_VIVANTE, CARCASSE, DECOUPE, ABATS, OEUFS, FERTILISANT, AUTRE — لا تعيد تسميته.', max_length=30, unique=True, verbose_name='الرمز')),
                ('libelle', models.CharField(max_length=150, verbose_name='التسمية')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نوع منتج نهائي',
                'verbose_name_plural': 'أنواع المنتجات النهائية',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AlterModelOptions(
            name='produitfini',
            options={'ordering': ['type_produit__ordre', 'designation'], 'verbose_name': 'منتج نهائي', 'verbose_name_plural': 'المنتجات النهائية'},
        ),
        migrations.AlterField(
            model_name='produitfini',
            name='unite_mesure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits_finis', to='intrants.unitemesure', verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='traitementfertilisant',
            name='produit_fini',
            field=models.ForeignKey(limit_choices_to={'type_produit__code': 'FERTILISANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='traitements_fertilisant', to='production.produitfini', verbose_name='المنتج النهائي (السماد)'),
        ),
        migrations.AlterField(
            model_name='produitfini',
            name='type_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits_finis', to='production.typeproduitfini', verbose_name='نوع المنتج'),
        ),
    ]
