# Generated by Django 6.0.3 on 2026-05-14 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0002_alter_consommation_options_alter_lotelevage_options_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionligne',
            options={'verbose_name': 'سطر إنتاج', 'verbose_name_plural': 'أسطر الإنتاج'},
        ),
        migrations.AlterModelOptions(
            name='productionrecord',
            options={'ordering': ['-date_production'], 'verbose_name': 'سجل إنتاج', 'verbose_name_plural': 'سجلات الإنتاج'},
        ),
        migrations.AlterModelOptions(
            name='produitfini',
            options={'ordering': ['type_produit', 'designation'], 'verbose_name': 'منتج نهائي', 'verbose_name_plural': 'المنتجات النهائية'},
        ),
        migrations.AlterField(
            model_name='productionligne',
            name='cout_unitaire_estime',
            field=models.DecimalField(decimal_places=4, default=0, help_text='مخصص من التكلفة الإجمالية للدفعة.', max_digits=12, verbose_name='التكلفة الوحدوية المقدرة (د.ج)'),
        ),
        migrations.AlterField(
            model_name='productionligne',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='productionligne',
            name='poids_unitaire_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='الوزن لكل وحدة (كغ)'),
        ),
        migrations.AlterField(
            model_name='productionligne',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='production.productionrecord', verbose_name='سجل الإنتاج'),
        ),
        migrations.AlterField(
            model_name='productionligne',
            name='produit_fini',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_production', to='production.produitfini', verbose_name='المنتج النهائي'),
        ),
        migrations.AlterField(
            model_name='productionligne',
            name='quantite',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية المنتجة'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='date_production',
            field=models.DateField(verbose_name='تاريخ الإنتاج / الذبح'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='elevage.lotelevage', verbose_name='دفعة التربية'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='nombre_oiseaux_abattus',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الطيور المذبوحة / المحصودة'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='poids_moyen_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='يُحسب تلقائياً إذا تم إدخال الوزن الإجمالي.', max_digits=8, verbose_name='متوسط الوزن لكل طير (كغ)'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='poids_total_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن الإجمالي (كغ)'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'مسودة'), ('valide', 'معتمد')], default='brouillon', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='produitfini',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='produitfini',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='التسمية'),
        ),
        migrations.AlterField(
            model_name='produitfini',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='produitfini',
            name='prix_vente_defaut',
            field=models.DecimalField(decimal_places=2, default=0, help_text='يُملأ مسبقاً في أسطر وصل تسليم العميل — قابل للتعديل.', max_digits=12, verbose_name='سعر البيع الافتراضي (د.ج)'),
        ),
        migrations.AlterField(
            model_name='produitfini',
            name='type_produit',
            field=models.CharField(choices=[('volaille_vivante', 'دواجن حية'), ('carcasse', 'ذبيحة كاملة'), ('decoupe', 'قطع'), ('abats', 'مخلفات الذبح'), ('oeufs', 'بيض'), ('autre', 'أخرى')], default='volaille_vivante', max_length=30, verbose_name='نوع المنتج'),
        ),
        migrations.AlterField(
            model_name='produitfini',
            name='unite_mesure',
            field=models.CharField(choices=[('unite', 'وحدة / رأس'), ('kg', 'كيلوغرام (كغ)'), ('plateau', 'صينية'), ('caisse', 'صندوق'), ('paquet', 'طرد')], default='unite', max_length=20, verbose_name='وحدة القياس'),
        ),
    ]
