# Generated by Django 6.0.3 on 2026-06-20 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrants', '0003_batiment_categorie_stockage_batiment_type_batiment_and_more'),
        ('production', '0002_alter_productionligne_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitfini',
            name='type_produit',
            field=models.CharField(choices=[('volaille_vivante', 'دواجن حية'), ('carcasse', 'ذبيحة كاملة'), ('decoupe', 'قطع'), ('abats', 'مخلفات الذبح'), ('oeufs', 'بيض'), ('fertilisant', 'سماد معالج'), ('autre', 'أخرى')], default='volaille_vivante', max_length=30, verbose_name='نوع المنتج'),
        ),
        migrations.CreateModel(
            name='TraitementFertilisant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_traitement', models.DateField(verbose_name='تاريخ المعالجة')),
                ('methode', models.CharField(blank=True, help_text='مثال: تجفيف، تخمير، معالجة حرارية...', max_length=255, verbose_name='طريقة المعالجة')),
                ('quantite_obtenue_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية النهائية المتحصل عليها (كغ)')),
                ('cout_unitaire_estime', models.DecimalField(decimal_places=4, default=0, help_text='تُستخدم لحساب متوسط تكلفة الإنتاج عبر المعادلة الموزونة.', max_digits=12, verbose_name='التكلفة الوحدوية المقدرة (د.ج)')),
                ('statut', models.CharField(choices=[('brouillon', 'مسودة'), ('valide', 'معتمد')], default='brouillon', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements_fertilisant_enregistres', to=settings.AUTH_USER_MODEL)),
                ('produit_fini', models.ForeignKey(limit_choices_to={'type_produit': 'fertilisant'}, on_delete=django.db.models.deletion.PROTECT, related_name='traitements_fertilisant', to='production.produitfini', verbose_name='المنتج النهائي (السماد)')),
            ],
            options={
                'verbose_name': 'معالجة سماد',
                'verbose_name_plural': 'عمليات معالجة السماد',
                'ordering': ['-date_traitement'],
            },
        ),
        migrations.CreateModel(
            name='CollecteFertilisant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collecte', models.DateField(verbose_name='تاريخ الجمع')),
                ('quantite_brute_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية الخام (كغ)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectes_fertilisant', to='intrants.batiment', verbose_name='المبنى')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_fertilisant_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('traitement', models.ForeignKey(blank=True, help_text='يُملأ عند تخصيص هذه الكمية الخام لعملية معالجة (دفعة).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes', to='production.traitementfertilisant', verbose_name='عملية المعالجة')),
            ],
            options={
                'verbose_name': 'جمع سماد خام',
                'verbose_name_plural': 'عمليات جمع السماد الخام',
                'ordering': ['-date_collecte'],
            },
        ),
    ]
