# Generated by Django 4.2.30 on 2026-06-30 22:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='تاريخ البدء')),
                ('date_fin', models.DateField(blank=True, help_text='اتركه فارغاً لاشتراك مستمر بدون تاريخ نهاية محدد.', null=True, verbose_name='تاريخ الانتهاء')),
                ('frequence', models.CharField(choices=[('mensuel', 'شهري'), ('personnalise', 'مخصص')], default='mensuel', max_length=20, verbose_name='التواتر')),
                ('quantite_totale_prevue', models.DecimalField(decimal_places=3, default=0, help_text='0 = بدون سقف كمية (تُتابع التسليمات بدون حد أقصى).', max_digits=14, verbose_name='الكمية الإجمالية المتعاقد عليها')),
                ('prix_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة (د.ج)')),
                ('statut', models.CharField(choices=[('actif', 'نشط'), ('termine', 'منتهٍ'), ('suspendu', 'معلّق')], default='actif', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements_client', to='core.branche', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'اشتراك عميل',
                'verbose_name_plural': 'اشتراكات العملاء',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='BLClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='مرجع وصل التسليم')),
                ('date_bl', models.DateField(verbose_name='تاريخ وصل التسليم')),
                ('adresse_livraison', models.TextField(blank=True, verbose_name='عنوان التسليم')),
                ('statut', models.CharField(choices=[('brouillon', 'مسودة'), ('livre', 'تم التسليم'), ('facture', 'مفوتر'), ('litige', 'في نزاع')], default='brouillon', max_length=20, verbose_name='الحالة')),
                ('signe_par', models.CharField(blank=True, max_length=150, verbose_name='موقّع من قبل (المستلم)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bls_client', to='core.branche', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'وصل تسليم العميل',
                'verbose_name_plural': 'وصولات تسليم العملاء',
                'ordering': ['-date_bl', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('adresse', models.TextField(blank=True, verbose_name='العنوان')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='الولاية')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('telephone_2', models.CharField(blank=True, max_length=30, verbose_name='الهاتف 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF')),
                ('rc', models.CharField(blank=True, max_length=50, verbose_name='RC')),
                ('contact_nom', models.CharField(blank=True, max_length=150, verbose_name='اسم جهة الاتصال')),
                ('type_client', models.CharField(choices=[('grossiste', 'تاجر جملة'), ('detaillant', 'تاجر تجزئة'), ('restauration', 'مطاعم / فندقة'), ('particulier', 'فرد'), ('autre', 'أخرى')], default='grossiste', max_length=20, verbose_name='نوع العميل')),
                ('plafond_credit', models.DecimalField(decimal_places=2, default=0, help_text='0 = لا يوجد حد محدد.', max_digits=14, verbose_name='سقف الائتمان (د.ج)')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FactureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='مرجع الفاتورة')),
                ('date_facture', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ قبل الضريبة (د.ج)')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, help_text='0 إذا كان معفى.', max_digits=5, verbose_name='نسبة الضريبة على القيمة المضافة (%)')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ الضريبة على القيمة المضافة (د.ج)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ شامل الضريبة (د.ج)')),
                ('montant_regle', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المسدد (د.ج)')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المتبقي (د.ج)')),
                ('statut', models.CharField(choices=[('non_payee', 'غير مدفوعة'), ('partiellement_payee', 'مدفوعة جزئياً'), ('payee', 'مدفوعة'), ('en_litige', 'في نزاع')], default='non_payee', max_length=25, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bls', models.ManyToManyField(blank=True, related_name='factures', to='clients.blclient', verbose_name='وصولات التسليم المضمنة')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_client', to='core.branche', verbose_name='الفرع')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_client', to='clients.client', verbose_name='العميل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_client_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فاتورة العميل',
                'verbose_name_plural': 'فواتير العملاء',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='PaiementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(verbose_name='تاريخ الدفع')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ (د.ج)')),
                ('mode_paiement', models.CharField(choices=[('especes', 'نقداً'), ('cheque', 'شيك'), ('virement', 'تحويل بنكي'), ('autre', 'أخرى')], default='especes', max_length=20, verbose_name='طريقة الدفع')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='المرجع (رقم الشيك / التحويل)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_client', to='core.branche', verbose_name='الفرع')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='clients.client', verbose_name='العميل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_client_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دفع العميل',
                'verbose_name_plural': 'مدفوعات العملاء',
                'ordering': ['-date_paiement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoyageLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_voyage', models.DateField(verbose_name='تاريخ الرحلة')),
                ('chauffeur', models.CharField(blank=True, max_length=150, verbose_name='السائق')),
                ('vehicule', models.CharField(blank=True, max_length=100, verbose_name='المركبة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages_livraison_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رحلة توصيل',
                'verbose_name_plural': 'رحلات التوصيل',
                'ordering': ['-date_voyage'],
            },
        ),
        migrations.CreateModel(
            name='PaiementClientAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_alloue', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ المخصص (د.ج)')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='clients.factureclient', verbose_name='الفاتورة')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='clients.paiementclient', verbose_name='الدفع')),
            ],
            options={
                'verbose_name': 'تخصيص دفع العميل',
                'verbose_name_plural': 'تخصيصات مدفوعات العملاء',
            },
        ),
        migrations.CreateModel(
            name='LivraisonPartielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ التسليم')),
                ('quantite_livree', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية المسلَّمة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='clients.abonnementclient', verbose_name='الاشتراك')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_partielles_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='clients.voyagelivraison', verbose_name='رحلة التوصيل')),
            ],
            options={
                'verbose_name': 'تسليم جزئي',
                'verbose_name_plural': 'التسليمات الجزئية',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BLClientLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية')),
                ('prix_unitaire', models.DecimalField(decimal_places=4, default=0, help_text='يُملأ مسبقاً من سعر البيع الافتراضي للمنتج النهائي.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة (د.ج)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='clients.blclient', verbose_name='وصل تسليم العميل')),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bl_client', to='production.produitfini', verbose_name='المنتج النهائي')),
            ],
            options={
                'verbose_name': 'سطر وصل تسليم العميل',
                'verbose_name_plural': 'أسطر وصل تسليم العملاء',
            },
        ),
        migrations.AddField(
            model_name='blclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bls_client', to='clients.client', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='blclient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bls_client_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abonnementclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='clients.client', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='abonnementclient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_client_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abonnementclient',
            name='produit_fini',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='production.produitfini', verbose_name='المنتج النهائي'),
        ),
        migrations.CreateModel(
            name='PrixMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ السعر')),
                ('prix_marche', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر السوق (د.ج/وحدة)')),
                ('source', models.CharField(blank=True, help_text='مثال: ONAB، السوق المحلي، إلخ.', max_length=100, verbose_name='المصدر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prix_marche_saisis', to=settings.AUTH_USER_MODEL)),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prix_marche', to='production.produitfini', verbose_name='المنتج النهائي')),
            ],
            options={
                'verbose_name': 'سعر السوق',
                'verbose_name_plural': 'أسعار السوق',
                'ordering': ['-date'],
                'unique_together': {('produit_fini', 'date')},
            },
        ),
    ]
