# Generated by Django 6.0.3 on 2026-05-01 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='Wilaya')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('telephone_2', models.CharField(blank=True, max_length=30, verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF')),
                ('rc', models.CharField(blank=True, max_length=50, verbose_name='RC')),
                ('contact_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom du contact')),
                ('type_client', models.CharField(choices=[('grossiste', 'Grossiste'), ('detaillant', 'Détaillant'), ('restauration', 'Restauration / Hôtellerie'), ('particulier', 'Particulier'), ('autre', 'Autre')], default='grossiste', max_length=20, verbose_name='Type de client')),
                ('plafond_credit', models.DecimalField(decimal_places=2, default=0, help_text='0 = pas de limite configurée.', max_digits=14, verbose_name='Plafond de crédit (DZD)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='BLClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence BL')),
                ('date_bl', models.DateField(verbose_name='Date du BL')),
                ('adresse_livraison', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('livre', 'Livré'), ('facture', 'Facturé'), ('litige', 'En litige')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('signe_par', models.CharField(blank=True, max_length=150, verbose_name='Signé par (réceptionnaire)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bls_client_crees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bls_client', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'BL Client',
                'verbose_name_plural': 'BL Clients',
                'ordering': ['-date_bl', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BLClientLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=4, default=0, help_text='Pré-rempli depuis prix_vente_defaut du produit fini.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire (DZD)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='clients.blclient', verbose_name='BL Client')),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bl_client', to='production.produitfini', verbose_name='Produit fini')),
            ],
            options={
                'verbose_name': 'Ligne BL Client',
                'verbose_name_plural': 'Lignes BL Client',
            },
        ),
        migrations.CreateModel(
            name='FactureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence facture')),
                ('date_facture', models.DateField(verbose_name='Date de la facture')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant HT (DZD)')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, help_text='0 si exonéré.', max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TVA (DZD)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TTC (DZD)')),
                ('montant_regle', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant réglé (DZD)')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Reste à payer (DZD)')),
                ('statut', models.CharField(choices=[('non_payee', 'Non payée'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('en_litige', 'En litige')], default='non_payee', max_length=25, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bls', models.ManyToManyField(blank=True, related_name='factures', to='clients.blclient', verbose_name='BL inclus')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_client', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_client_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture Client',
                'verbose_name_plural': 'Factures Clients',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='PaiementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(verbose_name='Date du paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant (DZD)')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence (n° chèque / virement)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_client_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement Client',
                'verbose_name_plural': 'Paiements Clients',
                'ordering': ['-date_paiement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaiementClientAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_alloue', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant alloué (DZD)')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='clients.factureclient', verbose_name='Facture')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='clients.paiementclient', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Allocation Paiement Client',
                'verbose_name_plural': 'Allocations Paiements Clients',
            },
        ),
    ]
