# Generated by Django 4.2.30 on 2026-07-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مفتاح ثابت: GROSSISTE, DETAILLANT, RESTAURATION, PARTICULIER, AUTRE — لا تعيد تسميته.', max_length=30, unique=True, verbose_name='الرمز')),
                ('libelle', models.CharField(max_length=150, verbose_name='التسمية')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نوع العميل',
                'verbose_name_plural': 'أنواع العملاء',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.typeclient', verbose_name='نوع العميل'),
        ),
    ]
