# Generated by Django 6.0.3 on 2026-05-14 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('production', '0002_alter_productionligne_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blclient',
            options={'ordering': ['-date_bl', '-created_at'], 'verbose_name': 'وصل تسليم العميل', 'verbose_name_plural': 'وصولات تسليم العملاء'},
        ),
        migrations.AlterModelOptions(
            name='blclientligne',
            options={'verbose_name': 'سطر وصل تسليم العميل', 'verbose_name_plural': 'أسطر وصل تسليم العملاء'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom'], 'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='factureclient',
            options={'ordering': ['-date_facture'], 'verbose_name': 'فاتورة العميل', 'verbose_name_plural': 'فواتير العملاء'},
        ),
        migrations.AlterModelOptions(
            name='paiementclient',
            options={'ordering': ['-date_paiement', '-created_at'], 'verbose_name': 'دفع العميل', 'verbose_name_plural': 'مدفوعات العملاء'},
        ),
        migrations.AlterModelOptions(
            name='paiementclientallocation',
            options={'verbose_name': 'تخصيص دفع العميل', 'verbose_name_plural': 'تخصيصات مدفوعات العملاء'},
        ),
        migrations.AlterField(
            model_name='blclient',
            name='adresse_livraison',
            field=models.TextField(blank=True, verbose_name='عنوان التسليم'),
        ),
        migrations.AlterField(
            model_name='blclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bls_client', to='clients.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='blclient',
            name='date_bl',
            field=models.DateField(verbose_name='تاريخ وصل التسليم'),
        ),
        migrations.AlterField(
            model_name='blclient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='blclient',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='مرجع وصل التسليم'),
        ),
        migrations.AlterField(
            model_name='blclient',
            name='signe_par',
            field=models.CharField(blank=True, max_length=150, verbose_name='موقّع من قبل (المستلم)'),
        ),
        migrations.AlterField(
            model_name='blclient',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'مسودة'), ('livre', 'تم التسليم'), ('facture', 'مفوتر'), ('litige', 'في نزاع')], default='brouillon', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='blclientligne',
            name='bl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='clients.blclient', verbose_name='وصل تسليم العميل'),
        ),
        migrations.AlterField(
            model_name='blclientligne',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='blclientligne',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=4, default=0, help_text='يُملأ مسبقاً من سعر البيع الافتراضي للمنتج النهائي.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة (د.ج)'),
        ),
        migrations.AlterField(
            model_name='blclientligne',
            name='produit_fini',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bl_client', to='production.produitfini', verbose_name='المنتج النهائي'),
        ),
        migrations.AlterField(
            model_name='blclientligne',
            name='quantite',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='client',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم جهة الاتصال'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='client',
            name='plafond_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = لا يوجد حد محدد.', max_digits=14, verbose_name='سقف الائتمان (د.ج)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=30, verbose_name='الهاتف 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('grossiste', 'تاجر جملة'), ('detaillant', 'تاجر تجزئة'), ('restauration', 'مطاعم / فندقة'), ('particulier', 'فرد'), ('autre', 'أخرى')], default='grossiste', max_length=20, verbose_name='نوع العميل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='bls',
            field=models.ManyToManyField(blank=True, related_name='factures', to='clients.blclient', verbose_name='وصولات التسليم المضمنة'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_client', to='clients.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='date_facture',
            field=models.DateField(verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ قبل الضريبة (د.ج)'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='montant_regle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المسدد (د.ج)'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ شامل الضريبة (د.ج)'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ الضريبة على القيمة المضافة (د.ج)'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='مرجع الفاتورة'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المتبقي (د.ج)'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='statut',
            field=models.CharField(choices=[('non_payee', 'غير مدفوعة'), ('partiellement_payee', 'مدفوعة جزئياً'), ('payee', 'مدفوعة'), ('en_litige', 'في نزاع')], default='non_payee', max_length=25, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='factureclient',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 إذا كان معفى.', max_digits=5, verbose_name='نسبة الضريبة على القيمة المضافة (%)'),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='clients.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='date_paiement',
            field=models.DateField(verbose_name='تاريخ الدفع'),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'نقداً'), ('cheque', 'شيك'), ('virement', 'تحويل بنكي'), ('autre', 'أخرى')], default='especes', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ (د.ج)'),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100, verbose_name='المرجع (رقم الشيك / التحويل)'),
        ),
        migrations.AlterField(
            model_name='paiementclientallocation',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='clients.factureclient', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='paiementclientallocation',
            name='montant_alloue',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ المخصص (د.ج)'),
        ),
        migrations.AlterField(
            model_name='paiementclientallocation',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='clients.paiementclient', verbose_name='الدفع'),
        ),
    ]
