# Generated by Django 4.2.30 on 2026-07-06 09:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_piecejointe'),
        ('clients', '0002_typeclient_alter_client_type_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ الأصلي (د.ج)')),
                ('montant_restant', models.DecimalField(decimal_places=2, help_text='يُنقص تلقائياً كلما استُهلك من أجل فاتورة جديدة.', max_digits=14, verbose_name='المبلغ المتبقي (د.ج)')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('utilise', models.BooleanField(default=False, help_text='يصبح True تلقائياً عندما montant_restant يصل إلى 0.', verbose_name='مستهلكة بالكامل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acomptes_client', to='core.branche', verbose_name='الفرع')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acomptes', to='clients.client', verbose_name='العميل')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acompte', to='clients.paiementclient', verbose_name='الدفع')),
            ],
            options={
                'verbose_name': 'دفعة مسبقة (عميل)',
                'verbose_name_plural': 'الدفعات المسبقة (العملاء)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationAcompteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_alloue', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ المخصص (د.ج)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acompte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='clients.acompteclient', verbose_name='الدفعة المسبقة')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations_acompte', to='clients.factureclient', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'تخصيص دفعة مسبقة (عميل)',
                'verbose_name_plural': 'تخصيصات الدفعات المسبقة (العملاء)',
            },
        ),
    ]
