# Generated by Django 6.0.3 on 2026-06-20 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_blclient_options_alter_blclientligne_options_and_more'),
        ('production', '0003_alter_produitfini_type_produit_traitementfertilisant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='تاريخ البدء')),
                ('date_fin', models.DateField(blank=True, help_text='اتركه فارغاً لاشتراك مستمر بدون تاريخ نهاية محدد.', null=True, verbose_name='تاريخ الانتهاء')),
                ('frequence', models.CharField(choices=[('mensuel', 'شهري'), ('personnalise', 'مخصص')], default='mensuel', max_length=20, verbose_name='التواتر')),
                ('quantite_totale_prevue', models.DecimalField(decimal_places=3, default=0, help_text='0 = بدون سقف كمية (تُتابع التسليمات بدون حد أقصى).', max_digits=14, verbose_name='الكمية الإجمالية المتعاقد عليها')),
                ('prix_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة (د.ج)')),
                ('statut', models.CharField(choices=[('actif', 'نشط'), ('termine', 'منتهٍ'), ('suspendu', 'معلّق')], default='actif', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='clients.client', verbose_name='العميل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_client_crees', to=settings.AUTH_USER_MODEL)),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='production.produitfini', verbose_name='المنتج النهائي')),
            ],
            options={
                'verbose_name': 'اشتراك عميل',
                'verbose_name_plural': 'اشتراكات العملاء',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='VoyageLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_voyage', models.DateField(verbose_name='تاريخ الرحلة')),
                ('chauffeur', models.CharField(blank=True, max_length=150, verbose_name='السائق')),
                ('vehicule', models.CharField(blank=True, max_length=100, verbose_name='المركبة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages_livraison_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رحلة توصيل',
                'verbose_name_plural': 'رحلات التوصيل',
                'ordering': ['-date_voyage'],
            },
        ),
        migrations.CreateModel(
            name='LivraisonPartielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ التسليم')),
                ('quantite_livree', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية المسلَّمة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='clients.abonnementclient', verbose_name='الاشتراك')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_partielles_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='clients.voyagelivraison', verbose_name='رحلة التوصيل')),
            ],
            options={
                'verbose_name': 'تسليم جزئي',
                'verbose_name_plural': 'التسليمات الجزئية',
                'ordering': ['-date'],
            },
        ),
    ]
