# Generated by Django 4.2.30 on 2026-07-10 18:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_acompteclient_allocationacompteclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='prixmarche',
            name='poids_reference_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('2.000'), help_text='وزن الصينية المرجعي (30 بيضة) الذي يقابل سعر السوق أعلاه — يُستخدم لتقدير السعر تناسبياً حسب الوزن الفعلي لعينة الدفعة (افتراضياً 2 كغ).', max_digits=6, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الوزن المرجعي للصينية (كغ)'),
        ),
    ]
