# Generated by Django 6.0.3 on 2026-06-29 20:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_abonnementclient_voyagelivraison_livraisonpartielle'),
        ('production', '0003_alter_produitfini_type_produit_traitementfertilisant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ السعر')),
                ('prix_marche', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر السوق (د.ج/وحدة)')),
                ('source', models.CharField(blank=True, help_text='مثال: ONAB، السوق المحلي، إلخ.', max_length=100, verbose_name='المصدر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prix_marche_saisis', to=settings.AUTH_USER_MODEL)),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prix_marche', to='production.produitfini', verbose_name='المنتج النهائي')),
            ],
            options={
                'verbose_name': 'سعر السوق',
                'verbose_name_plural': 'أسعار السوق',
                'ordering': ['-date'],
                'unique_together': {('produit_fini', 'date')},
            },
        ),
    ]
