# Generated by Django 4.2.30 on 2026-07-10 19:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_prixmarche_poids_reference_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementclient',
            name='mode_facturation',
            field=models.CharField(choices=[('quantite', 'بحسب الكمية المسلَّمة'), ('forfait', 'اشتراك جزافي (مبلغ ثابت دوري)')], default='quantite', max_length=20, verbose_name='نمط الفوترة'),
        ),
        migrations.AddField(
            model_name='abonnementclient',
            name='mode_paiement',
            field=models.CharField(choices=[('postpaye', 'بعدي — فاتورة تُصدر ثم تُسدَّد'), ('prepaye', 'مسبق — دفعة مقدمة تُستهلك تلقائياً عند الإصدار')], default='postpaye', help_text='مسبق: سجّل دفعة العميل قبل الإصدار فتُستهلك تلقائياً. بعدي: تُصدر الفاتورة أولاً.', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='abonnementclient',
            name='montant_forfait',
            field=models.DecimalField(decimal_places=2, default=0, help_text='يُستخدم فقط عندما تكون الفوترة «جزافية» — يُفوتر كل فترة بغض النظر عن الاستلام الفعلي.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ الجزافي الدوري (د.ج)'),
        ),
        migrations.AddField(
            model_name='factureclient',
            name='abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures_abonnement', to='clients.abonnementclient', verbose_name='الاشتراك (فوترة جزافية)'),
        ),
        migrations.AddField(
            model_name='factureclient',
            name='periode_debut',
            field=models.DateField(blank=True, null=True, verbose_name='بداية فترة الاشتراك المفوترة'),
        ),
        migrations.AddField(
            model_name='factureclient',
            name='periode_fin',
            field=models.DateField(blank=True, null=True, verbose_name='نهاية فترة الاشتراك المفوترة'),
        ),
        migrations.AlterField(
            model_name='abonnementclient',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=4, default=0, help_text='يُستخدم فقط عندما تكون الفوترة «بحسب الكمية المسلَّمة».', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة (د.ج)'),
        ),
        migrations.AddConstraint(
            model_name='factureclient',
            constraint=models.UniqueConstraint(condition=models.Q(('abonnement__isnull', False)), fields=('abonnement', 'periode_debut', 'periode_fin'), name='uniq_facture_abonnement_periode'),
        ),
    ]
