# Generated by Django 4.2.30 on 2026-07-10 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_abonnementclient_mode_facturation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraisonpartielle',
            name='quantite_livree',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='الكمية المسلَّمة'),
        ),
    ]
