# Generated by Django 4.2.30 on 2026-07-10 23:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intrants', '0002_unitemesure_alter_intrant_unite_mesure'),
        ('production', '0002_typeproduitfini_alter_produitfini_options_and_more'),
        ('clients', '0006_alter_livraisonpartielle_quantite_livree'),
    ]

    operations = [
        migrations.AddField(
            model_name='blclientligne',
            name='intrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bl_client', to='intrants.intrant', verbose_name='المدخل (فائض للبيع)'),
        ),
        migrations.AlterField(
            model_name='blclientligne',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=4, default=0, help_text='يُملأ مسبقاً من سعر البيع الافتراضي للمنتج النهائي، أو يُدخل يدويًا للمدخلات.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة (د.ج)'),
        ),
        migrations.AlterField(
            model_name='blclientligne',
            name='produit_fini',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bl_client', to='production.produitfini', verbose_name='المنتج النهائي'),
        ),
        migrations.AddConstraint(
            model_name='blclientligne',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('intrant__isnull', True), ('produit_fini__isnull', False)), models.Q(('intrant__isnull', False), ('produit_fini__isnull', True)), _connector='OR'), name='bl_client_ligne_un_seul_article'),
        ),
    ]
