# Generated by Django 4.2.30 on 2026-06-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieIntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مفتاح ثابت: ALIMENT, POUSSIN, MEDICAMENT, AUTRE — لا تعيد تسميته.', max_length=50, unique=True, verbose_name='الرمز')),
                ('libelle', models.CharField(max_length=150, verbose_name='التسمية')),
                ('consommable_en_lot', models.BooleanField(default=False, help_text='ضع علامة للفئات التي يمكن إدخالها في الاستهلاك.', verbose_name='قابل للاستهلاك في الدفعة')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فئة مدخل',
                'verbose_name_plural': 'فئات المدخلات',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='اسم المورد')),
                ('adresse', models.TextField(blank=True, verbose_name='العنوان')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='الولاية')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('telephone_2', models.CharField(blank=True, max_length=30, verbose_name='الهاتف 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF')),
                ('rc', models.CharField(blank=True, max_length=50, verbose_name='RC')),
                ('contact_nom', models.CharField(blank=True, max_length=150, verbose_name='اسم جهة الاتصال')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الرمز')),
                ('libelle', models.CharField(max_length=150, verbose_name='التسمية')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نوع المورد',
                'verbose_name_plural': 'أنواع الموردين',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Intrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='التسمية')),
                ('stade', models.CharField(choices=[('demarrage', 'بداية (كتاكيت / حضانة)'), ('croissance', 'نمو (دجاج لاحم)'), ('ponte', 'بيّاض (دجاج بيّاض)'), ('tous', 'كل المراحل')], default='tous', help_text='يحدد ما إذا كان هذا المدخل مخصصاً للكتاكيت (حضانة) أو الدجاج البالغ (نمو/بيّاض).', max_length=20, verbose_name='مرحلة الاستخدام')),
                ('unite_mesure', models.CharField(choices=[('kg', 'كيلوغرام (كغ)'), ('sac', 'كيس (25 كغ)'), ('unite', 'وحدة / رأس'), ('litre', 'لتر'), ('flacon', 'قارورة'), ('dose', 'جرعة'), ('ml', 'مليلتر (مل)'), ('g', 'غرام (غ)')], default='kg', max_length=20, verbose_name='وحدة القياس')),
                ('seuil_alerte', models.DecimalField(decimal_places=3, default=0, help_text='تنبيه إذا انخفض المخزون عن هذا الحد.', max_digits=12, verbose_name='حد تنبيه المخزون')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intrants', to='intrants.categorieintrant', verbose_name='الفئة')),
                ('fournisseurs', models.ManyToManyField(blank=True, related_name='intrants', to='intrants.fournisseur', verbose_name='الموردون المرتبطون')),
            ],
            options={
                'verbose_name': 'مدخل',
                'verbose_name_plural': 'المدخلات',
                'ordering': ['categorie__libelle', 'designation'],
            },
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='type_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fournisseurs', to='intrants.typefournisseur', verbose_name='النوع الرئيسي'),
        ),
        migrations.CreateModel(
            name='CategorieQualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='الرمز')),
                ('libelle', models.CharField(max_length=150, verbose_name='التسمية')),
                ('type_pesee', models.CharField(choices=[('oiseaux', 'طيور'), ('oeufs', 'بيض')], help_text='هل هذه الفئة لتصنيف الطيور أم البيض؟', max_length=10, verbose_name='نوع القياس')),
                ('poids_min', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الوزن الأدنى (غ)')),
                ('poids_max', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الوزن الأقصى (غ)')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فئة جودة',
                'verbose_name_plural': 'فئات الجودة',
                'ordering': ['type_pesee', 'ordre'],
                'unique_together': {('code', 'type_pesee')},
            },
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='الاسم / الرقم')),
                ('type_batiment', models.CharField(choices=[('poussiniere', 'حضانة كتاكيت (Poussinière)'), ('poulailler', 'حظيرة دجاج (تربية / بيض)'), ('entrepot', 'مستودع تخزين')], default='poulailler', max_length=20, verbose_name='نوع المبنى')),
                ('categorie_stockage', models.CharField(blank=True, choices=[('oeufs', 'بيض / أطباق'), ('fertilisant', 'سماد معالج')], help_text='يُملأ فقط عندما يكون نوع المبنى = مستودع.', max_length=20, verbose_name='نوع التخزين (للمستودعات فقط)')),
                ('capacite', models.PositiveIntegerField(blank=True, null=True, verbose_name='الطاقة الاستيعابية (رأس)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
                ('branche', models.ForeignKey(help_text='الفرع الذي ينتمي إليه هذا المبنى (BR-BRA-01) — لا يتغير بعد الإنشاء عملياً.', on_delete=django.db.models.deletion.PROTECT, related_name='batiments', to='core.branche', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'مبنى',
                'verbose_name_plural': 'المباني',
                'ordering': ['branche', 'nom'],
                'unique_together': {('branche', 'nom')},
            },
        ),
    ]
