# Generated by Django 6.0.3 on 2026-05-01 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom / Numéro')),
                ('capacite', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité (têtes)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Bâtiment',
                'verbose_name_plural': 'Bâtiments',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CategorieIntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Clé stable : ALIMENT, POUSSIN, MEDICAMENT, AUTRE — ne pas renommer.', max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=150, verbose_name='Libellé')),
                ('consommable_en_lot', models.BooleanField(default=False, help_text='Cocher pour les catégories pouvant être saisies en Consommation.', verbose_name='Consommable en lot')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Catégorie d'intrant",
                'verbose_name_plural': "Catégories d'intrants",
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du fournisseur')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='Wilaya')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('telephone_2', models.CharField(blank=True, max_length=30, verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF')),
                ('rc', models.CharField(blank=True, max_length=50, verbose_name='RC')),
                ('contact_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom du contact')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=150, verbose_name='Libellé')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de fournisseur',
                'verbose_name_plural': 'Types de fournisseurs',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Intrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('unite_mesure', models.CharField(choices=[('kg', 'Kilogramme (kg)'), ('sac', 'Sac (25 kg)'), ('unite', 'Unité / Tête'), ('litre', 'Litre'), ('flacon', 'Flacon'), ('dose', 'Dose'), ('ml', 'Millilitre (ml)'), ('g', 'Gramme (g)')], default='kg', max_length=20, verbose_name='Unité de mesure')),
                ('seuil_alerte', models.DecimalField(decimal_places=3, default=0, help_text='Alerte si le stock descend sous ce seuil.', max_digits=12, verbose_name="Seuil d'alerte stock")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intrants', to='intrants.categorieintrant', verbose_name='Catégorie')),
                ('fournisseurs', models.ManyToManyField(blank=True, related_name='intrants', to='intrants.fournisseur', verbose_name='Fournisseurs associés')),
            ],
            options={
                'verbose_name': 'Intrant',
                'verbose_name_plural': 'Intrants',
                'ordering': ['categorie__libelle', 'designation'],
            },
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='type_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fournisseurs', to='intrants.typefournisseur', verbose_name='Type principal'),
        ),
    ]
