# Generated by Django 6.0.3 on 2026-05-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batiment',
            options={'ordering': ['nom'], 'verbose_name': 'مبنى', 'verbose_name_plural': 'المباني'},
        ),
        migrations.AlterModelOptions(
            name='categorieintrant',
            options={'ordering': ['ordre', 'libelle'], 'verbose_name': 'فئة مدخل', 'verbose_name_plural': 'فئات المدخلات'},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['nom'], 'verbose_name': 'مورد', 'verbose_name_plural': 'الموردون'},
        ),
        migrations.AlterModelOptions(
            name='intrant',
            options={'ordering': ['categorie__libelle', 'designation'], 'verbose_name': 'مدخل', 'verbose_name_plural': 'المدخلات'},
        ),
        migrations.AlterModelOptions(
            name='typefournisseur',
            options={'ordering': ['ordre', 'libelle'], 'verbose_name': 'نوع المورد', 'verbose_name_plural': 'أنواع الموردين'},
        ),
        migrations.AlterField(
            model_name='batiment',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='capacite',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الطاقة الاستيعابية (رأس)'),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='الاسم / الرقم'),
        ),
        migrations.AlterField(
            model_name='categorieintrant',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='categorieintrant',
            name='code',
            field=models.CharField(help_text='مفتاح ثابت: ALIMENT, POUSSIN, MEDICAMENT, AUTRE — لا تعيد تسميته.', max_length=50, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='categorieintrant',
            name='consommable_en_lot',
            field=models.BooleanField(default=False, help_text='ضع علامة للفئات التي يمكن إدخالها في الاستهلاك.', verbose_name='قابل للاستهلاك في الدفعة'),
        ),
        migrations.AlterField(
            model_name='categorieintrant',
            name='libelle',
            field=models.CharField(max_length=150, verbose_name='التسمية'),
        ),
        migrations.AlterField(
            model_name='categorieintrant',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='contact_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم جهة الاتصال'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='اسم المورد'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=30, verbose_name='الهاتف 2'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='type_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fournisseurs', to='intrants.typefournisseur', verbose_name='النوع الرئيسي'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='intrant',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='intrant',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intrants', to='intrants.categorieintrant', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='intrant',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='التسمية'),
        ),
        migrations.AlterField(
            model_name='intrant',
            name='fournisseurs',
            field=models.ManyToManyField(blank=True, related_name='intrants', to='intrants.fournisseur', verbose_name='الموردون المرتبطون'),
        ),
        migrations.AlterField(
            model_name='intrant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='intrant',
            name='seuil_alerte',
            field=models.DecimalField(decimal_places=3, default=0, help_text='تنبيه إذا انخفض المخزون عن هذا الحد.', max_digits=12, verbose_name='حد تنبيه المخزون'),
        ),
        migrations.AlterField(
            model_name='intrant',
            name='unite_mesure',
            field=models.CharField(choices=[('kg', 'كيلوغرام (كغ)'), ('sac', 'كيس (25 كغ)'), ('unite', 'وحدة / رأس'), ('litre', 'لتر'), ('flacon', 'قارورة'), ('dose', 'جرعة'), ('ml', 'مليلتر (مل)'), ('g', 'غرام (غ)')], default='kg', max_length=20, verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='typefournisseur',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='typefournisseur',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='typefournisseur',
            name='libelle',
            field=models.CharField(max_length=150, verbose_name='التسمية'),
        ),
        migrations.AlterField(
            model_name='typefournisseur',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
    ]
