# Generated by Django 4.2.30 on 2026-07-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intrants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مفتاح ثابت (مثال: KG, SAC, UNITE) — لا تعيد تسميته.', max_length=20, unique=True, verbose_name='الرمز')),
                ('libelle', models.CharField(max_length=100, verbose_name='التسمية')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'وحدة قياس',
                'verbose_name_plural': 'وحدات القياس',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AlterField(
            model_name='intrant',
            name='unite_mesure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intrants', to='intrants.unitemesure', verbose_name='وحدة القياس'),
        ),
    ]
