# Generated by Django 4.2.30 on 2026-07-11 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intrants', '0002_unitemesure_alter_intrant_unite_mesure'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='يُملأ تلقائياً عند الإنشاء. يُستخدم لتقييد رؤية حساب السائق على الموردين الذين أنشأهم بنفسه فقط.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseurs_crees', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
    ]
