# Generated by Django 6.0.3 on 2026-06-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrants', '0002_alter_batiment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='categorie_stockage',
            field=models.CharField(blank=True, choices=[('oeufs', 'بيض / أطباق'), ('fertilisant', 'سماد معالج')], help_text='يُملأ فقط عندما يكون نوع المبنى = مستودع.', max_length=20, verbose_name='نوع التخزين (للمستودعات فقط)'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='type_batiment',
            field=models.CharField(choices=[('poussiniere', 'حضانة كتاكيت (Poussinière)'), ('poulailler', 'حظيرة دجاج (تربية / بيض)'), ('entrepot', 'مستودع تخزين')], default='poulailler', max_length=20, verbose_name='نوع المبنى'),
        ),
        migrations.AddField(
            model_name='intrant',
            name='stade',
            field=models.CharField(choices=[('demarrage', 'بداية (كتاكيت / حضانة)'), ('croissance', 'نمو (دجاج لاحم)'), ('ponte', 'بيّاض (دجاج بيّاض)'), ('tous', 'كل المراحل')], default='tous', help_text='يحدد ما إذا كان هذا المدخل مخصصاً للكتاكيت (حضانة) أو الدجاج البالغ (نمو/بيّاض).', max_length=20, verbose_name='مرحلة الاستخدام'),
        ),
        migrations.CreateModel(
            name='CategorieQualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='الرمز')),
                ('libelle', models.CharField(max_length=150, verbose_name='التسمية')),
                ('type_pesee', models.CharField(choices=[('oiseaux', 'طيور'), ('oeufs', 'بيض')], help_text='هل هذه الفئة لتصنيف الطيور أم البيض؟', max_length=10, verbose_name='نوع القياس')),
                ('poids_min', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الوزن الأدنى (غ)')),
                ('poids_max', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الوزن الأقصى (غ)')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فئة جودة',
                'verbose_name_plural': 'فئات الجودة',
                'ordering': ['type_pesee', 'ordre'],
                'unique_together': {('code', 'type_pesee')},
            },
        ),
    ]
